### ISSUE TITLE
Document: Cookie signature does not take cookie expiry into account

### ISSUE THREAD

**Issue by saxbophone** [expressjs/cookie-session#101]
The signature cookie does not appear to take the expiry date of the cookie it is signing into account.

This has some implications if one wants to enforce a strict no-activity logout time period, as the user can just set the expiry time of the cookie arbitrarily further in the future to circumvent this restriction.

This design might be by intention (and in fairness, it should be the application's responsibility to enforce such a policy, the session expiry time ought to be stored in the cookie itself rather than just use the cookie's expiry time, as I can imagine there being some valid uses for the expiry time of a cookie to be separate to the expiry of the login session), but as the example in the README (extended cookie/session expiry time) can imply that this could be used to extend the length of a login session it might be good to mention this in the example.

This is just a suggestion, mind (I'm acutely aware of the principle _do one thing well_) and this library ought not to concern itself too much with _what_ people are using it to store in sessions, nor indeed _why_ or _how_.

**Comment by dougwilson** [comment]
Yes, this is as designed; the signature can only validate what the browsers actually sends back to the server, which is only the value. The web browser doesn't provide any of the other cookie attributes in the request. Your solution is the right one if you want to actually limit the length of a session: include expiry in the session data.

You're welcome to make such a pull request to add such documentation :+1:

**Comment by dougwilson** [comment]
The docs currently here that describe what the signature does does already describe what exactly is being included in the hash, though.
