### ISSUE TITLE
Multiple Cookies

### ISSUE THREAD

**Issue by natanavra** [expressjs/cookie-session#102]
Is it possible to set multiple cookies with different names?
Using `app.use(cookieSession(config))` multiple times, overrides the previous ones.

**Comment by dougwilson** [comment]
Do you need to access the different sessions simultaneously or are you trying to use one session for some of your routes and another for a different subset of your routes? Ideally if you can outline fully what you're trying to accomplish I can better help :+1:

**Comment by natanavra** [comment]
@dougwilson Thanks for the response Doug.
I'd like to access different cookies on the same route.
The current setup involves an app level cookie middleware (so it's on all routes) and moving to a route level cookie would be a hassle.

**Comment by dougwilson** [comment]
Gotcha. Right now that is impossible, unfortunately. If you have an idea how to implement please share and feel free to even make a pull request :+1:

**Comment by natanavra** [comment]
I have an idea, hopefully will find the time to send a pull request

**Comment by natanavra** [comment]
After further thinking, I think that it's not a relevant use case for `cookie-session`, as it is meant to manage a session for a user and not to track many different users across domains, which is my use cases.
As I see it `cookie-session` is for managing things like login sessions.
For future reference: I resorted to using `cookie-parser` and managing cookies manually using the `req.signedCookies` object.
