### ISSUE TITLE
Support for GraphQl

### ISSUE THREAD

**Issue by rodolph66** [expressjs/cookie-session#103]
I'm not sure if I have been doing something wrong but I have tried various iterations of the same thing. cookie-session is simply not working with GraphQL. I'm not sure of the reason but when req (or req, res) is passed to the context of qraphql in express server, i.e.
 
`app.get('/graphql', graphqlExpress( (req, res) => ({
  schema,
  context: { req, res }
}) ))`

... setting req.session to any property/value (in the graphql resolver) simply does not trigger the set.cookie on the res. Inspecting the devtools on the browser shows no presence of any cookie. On the other hand, if I do not use cookie-session and set the cookie on the res myself using Express' res.cookie(), everything works correctly, the cookie is passed to the client and returned with subsequent requests.

**Comment by dougwilson** [comment]
Very strange. I can definitely take a look! How can I reproduce the issue?

**Comment by dougwilson** [comment]
Closing due to no response.
