### ISSUE TITLE
Deleting the session doesn't invalidate the token. Intended?

### ISSUE THREAD

**Issue by slavabez** [expressjs/cookie-session#106]
Hi! First off: thanks for all the work!

I was writing tests for my project that uses cookie-session with passport and the passport-local strategy. I had a test that checks the logout functionality of my API, with the following pseudo code:

1) Login with correct credentials at the login end-point
2) Save the session and session.sig cookies
3) Request a protected resource with the cookies attached, expect "access granted"
4) Call the logout end-point with the cookies attached, expect good response
5) Call the protected resource again with the same cookies, expecting "access denied"

Step 5 fails for me, even though I call `req.logout()` and set `req.session = null` it doesn't seem to invalidate the cookies assigned at step 1, I can still use those cookies to access protected end-points.
Is this intended functionality, or is there something wrong with my approach?

**Comment by dougwilson** [comment]
I'm not familiar with passport so not sure what is going on there or if you're thinking if there is a passport issue. As far as this module goes, all the data is stored in the cookie and there is no server side state, so it's not possible to invalidate a previous cookie value unless you add some kind of identifier in the value and store it on your server to check against.

I hope this helps.

**Comment by slavabez** [comment]
Gotcha, thanks for clearing it up for me!
