### ISSUE TITLE
session is empty when use express.router()

### ISSUE THREAD

**Issue by d-jiang** [expressjs/cookie-session#107]
from the instruction, cookie-session will auto set a cookie in browser,
but it seems like doesn't work in my project.

node --version v10.8.0
"express": "~4.16.0",
"cookie-session": "^2.0.0-beta.3",

express.Router() has been used in my project.

The code below is configuration of cookie-session in app.js
```
app.use(cookieSession({
  name: 'session', 
  keys: confs.sessionKeys(), 
  maxAge: 7 * 24 * 60 * 60 * 1000 
})
```
in router/index.js
```

const express = require('express');

const router = express.Router();

router.use(function (req, res, next) {
  req.session.views = (req.session.views || 0) + 1;
  res.end(req.session.views + ' views');
  console.log(req.session.count);
  next();
});
```
and the output is empty.

Thanks

**Comment by dougwilson** [comment]
Sorry you're having trouble. I can investigate the issue, though. Please provide all the following so I can reproduce the issue:

1. Complete source code I can copy and paste and run without modification.
2. Complete instructions on how to reproduce the issue after running the above code.

Thanks!

**Comment by d-jiang** [comment]
@dougwilson thanks for the excellent work. I'm new to backend, I think this "issue" is causing my misunderstanding of session. 

0. run node and check the cookie (cookie auto set by cookie-session)
1. cleaned cookies manually 
2. change port and restart node
3. cookie not reset

I think the issue is caused by I have not restart my browser. 

Thanks for ur reply.

**Comment by d-jiang** [comment]
https://github.com/d-jiang/cookie-session_example.git

as a demo, I haven't delete node_modules, so just download and run `npm start`

Thank you.

**Comment by dougwilson** [comment]
Thank you @d-jiang . I can run your code, but I don't understand the instructions I'm supposed to follow. To see the issue.

**Comment by d-jiang** [comment]
@dougwilson Sorry for the delay reply, I use jsonwebtoken instead of session. 
Thank you for your help.
