### ISSUE TITLE
Set-Cookie on OPTIONS calls.

### ISSUE THREAD

**Issue by frederikhors** [expressjs/cookie-session#109]
I'm using this package in an express 4 server with CORS.

Today I noticed a Set-Cookie for the preflight OPTIONS calls.

I think this is wrong. Isn't it?

After the OPTIONS preflight calls the cookie is the old one, like the Set-Cookie in OPTIONS call Response header didn't anything.

This is strange, right?

**Comment by dougwilson** [comment]
This module is not aware of CORS and the `OPTIONS` method is used for more than just CORS. If you don't want the cookie to be set on a particular request, do not allow the request to enter the middleware, just like if you wanted any other middleware to not apply to a given request 👍

**Comment by dougwilson** [comment]
Also note that the module only sets the cookie if you added something to `req.session`. So you can also just not put anything into `req.session` on a preflight call (or any other call you don't want the cookie to set on) and then it won't set. Adding a value into `req.session` is a signal that you _want_ that value to be persisted into the cookie.

**Comment by frederikhors** [comment]
I think this behavior is for this: https://github.com/expressjs/csurf/issues/162
