### ISSUE TITLE
Share cookie session between multiple domain

### ISSUE THREAD

**Issue by Cwanyo** [expressjs/cookie-session#111]
I would like to know whether is it possible to share the [cookie session](https://github.com/expressjs/cookie-session) across multiple domain according to the scenario below :-

I have 2 restful web service servers hosted on different domains, each server connected to the specific database (setup as master and slave for load balancing purpose).

<pre>
WebApp <--> Load Balancer(www.lb.com) <--(All HTTP Methods)--> R1(www.r1.com) <--(Read/Write)--> DB-Master
                     ^-----------------(GET Method Only)-----> R2(www.r2.com) <--(Read Only)--> DB-Slave
</pre>

Basically, R1 and R2 server have the same instant(same code). But, R2 is limited to read function only because the db is in the slave mode (sync from master).

The problem here is that, the authentication (login) is required on both R1 and R2 in order to access some functions which is controlled by middleware. Let's assume that users have to login only once in R1.

I know that the cookie session that created from R1 can be used in R2, if both server use the same "secret key". I tried it on postman and it worked. However, I don't know whether the cookie session that created from the R1 can be shared programmatically to R2 or not. 

And If I understand correctly, the [load balancer](https://thecodebarbarian.com/building-your-own-load-balancer-with-express-js) will act as a pipe that will send all the request across the servers that are in the list. So, I don't think it is a good idea to do the authentication at the load balancer node.

So can you please give me the suggestion. I tried searching on the stackoverflow but no luck.

Thank you.

**Comment by dougwilson** [comment]
As far as I know, it's not possible to do this. Web browsers will not allow a single cookie to work on both www.r1.com and www.r2.com
