### ISSUE TITLE
Is this really still in 3rd "beta" for over a year !?!

### ISSUE THREAD

**Issue by bjbrewster** [expressjs/cookie-session#112]
Just wondering why this is still in 3rd "beta" when it's been the latest published version in NPM since Oct 2017 and with over 70K weekly downloads.  

Surely this is being used in production and can finally be blessed as 2.0.0.

Regards,
Brendan

**Comment by dougwilson** [comment]
Are the 70K downloads for 1.x or the 2 beta? The last 1.x was published around the same time beta 3 was of 2 (both near the end of 2017).

I have a lot going on so didn't really remember this was still a beta 2. I can promote it, though I believe there are still some known issues, but will need to take a look and refresh myself on this likely in jan when I get some time.

How log have you used the beta and has it worked well for you?

**Comment by bjbrewster** [comment]
I'm not sure how to check the version breakdown of the downloads stat on the npm package page but anyone since October last year using 'npm install cookie-session' has been using the `2.0.0-beta.3` version.  I've had no problem with it myself in our production websites over the last year.

**Comment by dougwilson** [comment]
How would that be? I only set the beta to "latest" in Oct 2018, not when I initially published it. You can alter what latest is outside of publishes to npm by just changing what a tag points to.

I was trying to get some more exposure to the beta before promoting, though it has not been latest for very long.
