### ISSUE TITLE
Session does not get stored if keys is not an array

### ISSUE THREAD

**Issue by AndrewVos** [expressjs/cookie-session#113]
Setting `keys` to a string causes `cookie-session` to fail silently.

Nothing will be stored in the session, and no errors are shown.

**Comment by dougwilson** [comment]
Thanks for the report. To clarify are using the beta version or stable version?

**Comment by AndrewVos** [comment]
I'm not at a computer right now but I just ran a yarn install with the default version. This was yesterday.

**Comment by dougwilson** [comment]
Thanks. Any news on which version you're using yet? I can reopen once provided, since no further information has been provided in a few days. Ideally if there is code and steps to reproduce that would help, but right now there is limited information here to act on.
