### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by CaitlinWeb** [expressjs/cookie-session#118]
@dougwilson I'm curious to know if there is any plans to finalize version 2 as it's still marked as beta. Related to that, is this project no longer being actively maintained? (With 300,000+ downloads a month, that would be a shame.)

Is version 2 as-is suitable for production or should I use version 1?

**Comment by dougwilson** [comment]
I think I have the answers to this in #112. Let me know if you have additional questions on top of that and I'm happy to answer.

Yes, I am maintaining this actively. Still need to fix the issues in the beta but I'll always accept PRs to the effect.

**Comment by dougwilson** [comment]
> Is version 2 as-is suitable for production or should I use version 1?

As far as this goes, I think that semver would help answer that. If you are ok running beta code in production, feel free and you can help provide feedback on issues you encounter with other modules that use req.session , for example.

If you want the non beta version, you're welcome to use it just as well and even if you have issues there 1.x releases can be released with fixes (and they have been already).

**Comment by CaitlinWeb** [comment]
Thanks for the quick response! That answered my questions. Kudos!
