### ISSUE TITLE
error ERR_HTTP_HEADERS_SENT when updating from socket

### ISSUE THREAD

**Issue by fithwith** [expressjs/cookie-session#121]
I have the below code which is sharing the session between express and socketio.

`
var sesmid=cookieSession({
    name: 'session',
    keys: ['123'],
    maxAge: 24 * 60 * 60 * 1000 // 24 hours
  })
app.use(sesmid)
iolib.use(function(socket, next) {
    sesmid(socket.request, socket.request.res, next);
});
`

when I'm trying to update the session from the socket using the below code 
`
socket.request.session.aaa=5;
socket.request.session.save();
`
I'm getting :
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

**Comment by dougwilson** [comment]
Since the data is stored in the cookie, it's not possible to alter the data after the cookie has been sent from the request.

**Comment by fithwith** [comment]
but I didn't send the data, when the event is fired on the server side the first thing that I'm trying to execute is 
`socket.request.session.aaa=5;  socket.request.session.save();`

**Comment by dougwilson** [comment]
Is it possible to provide either a fix for the issue as a pull request or a full reproduction case and instructions for how to see the issue? Otherwise in the end I am just speculating.

**Comment by dougwilson** [comment]
Closing due to no response.
