### ISSUE TITLE
What is holding back the 2.x release?

### ISSUE THREAD

**Issue by oliversalzburg** [expressjs/cookie-session#122]
I was wondering why the 2.x has been standing for so long. What needs to be done?

**Comment by dougwilson** [comment]
Duplicate of #118 I believe. Let me know if you have any additional specific questions. Really I haven't migrated most of my production to 2.x yet so I am just not confident in it. If you say it works great in production as it is, I can publish as 2.0.

**Comment by oliversalzburg** [comment]
I just bumped our dependency to 2.0.0-beta.3. I'll report back
