### ISSUE TITLE
How to set maxAge per request

### ISSUE THREAD

**Issue by JuneQuev** [expressjs/cookie-session#123]
I want to use persistent cookies for mobile devices and session cookies for everything else.  Following the package documentation for per user sticky max age example, I did the following which does not work:
```js
const session = require('cookie-session');
  app.use(session(getSessionOptions(authConfig)));

  app.use(function (req, res, next) {
    if (isMobileRequest(req)) {
      req.sessionOptions.maxAge = openid.session.maxAge;
    }
    next();
  });
```

If I modify the session-cookie index.js to set the maxAge for mobile devices at the time of session creation, I get the desired result, but I don't want to modify this library.  Any ideas about why this is not working?

**Comment by dougwilson** [comment]
Hi @JuneQuev thanks for the report. I tried on my machine with a simple demo and wasn't able to reproduce the issue. It is possible there is more going on in your app that may be conflicting with the behavior. Can you help provide the following information so I can check it out?

1. Version of this module you're using
2. Version of Node.js
3. Complete code that I can run that demonstrates the issue
4. Instructions for how to reproduce with the above code.

Thank you!

**Comment by dougwilson** [comment]
Closing due to no response.
