### ISSUE TITLE
Modifying a cookie

### ISSUE THREAD

**Issue by Crowbrammer** [expressjs/cookie-session#125]
I'm curious about how to use cookies, esp. with cookie-session.

Specifically, I want to update a cookie after interacting with an Express server.

An example: I expected the view counter to work out of the box:

```js
app.use(cookieSession({
  name: 'session',
  keys: ['key1', 'key2']
}))
 
app.use(function (req, res, next) {
  var n = req.session.views || 0
  req.session.views = n++
  res.end(n + ' views')
})
 
app.listen(3000)
```
Actual: Every relative link I visit returns "1 views". 

I searched through the issues, the documentation, YT videos, and other cookie modules. 

How do you update a cookie with cookie-session? I'm trying to use cookie-session for this, else I'd use cookie-parser to accomplish the result.

**Comment by dougwilson** [comment]
`n++` is called post-increment, which means that the number is added to `n` _after_ the value is returned. So that would mean that `n` will always be stored as `0` in your example and you'll always see `1 views` on the page.

Use `++n` instead or even `n + 1` if you want the final, incremented value to be stored in your session cookie.

**Comment by dougwilson** [comment]
You can find a working example of what you have above in the README: https://github.com/expressjs/cookie-session#simple-view-counter-example

**Comment by Crowbrammer** [comment]
Much appreciated @dougwilson ! I grabbed this example from [the npm doc](https://www.npmjs.com/package/cookie-session), so the n++ didn't register.

Thanks for spotting that!

**Comment by dougwilson** [comment]
Oh, wow, didn't realize the npm doc had something different, sorry for that! I will get the npm doc updated.

**Comment by jaschaio** [comment]
@dougwilson I run into the same issue. The example is quite confusing

**Comment by dougwilson** [comment]
@jaschaio pull requests are welcome to improve the examples. Just saying they are confusing without providing a path to make them not confusing doesn't really help :)
