### ISSUE TITLE
sess.sig issue

### ISSUE THREAD

**Issue by EmmyMay** [expressjs/cookie-session#127]
sess.sig is stuffed in the cookie and sent to the browser even when cookie-sesson,signed is not set. This is hindering logging out of the app.

**Comment by dougwilson** [comment]
Hi @EmmyMay thanks for the report. I tried on my machine with a simple demo and wasn't able to reproduce the issue. Can you help provide the following information so I can check it out?

1. Version of this module you're using
2. Version of Node.js
3. Complete code that I can run that demonstrates the issue
4. Instructions for how to reproduce with the above code.

Thank you!

**Comment by dougwilson** [comment]
Closing due to no response.
