### ISSUE TITLE
Document: Ambiguity in Signature Documentation

### ISSUE THREAD

**Issue by tncbbthositg** [expressjs/cookie-session#128]
Thanks for maintaining this module!  It's super helpful.  

I was looking at the `signed` documentation and I was concerned that the SHA1 signature might be implemented in such a way that it is susceptible to length extension attacks.

> signed: a boolean indicating whether the cookie is to be signed (true by default). If this is true, another cookie of the same name with the .sig suffix appended will also be sent, with a 27-byte url-safe base64 SHA1 value representing the hash of cookie-name=cookie-value against the first Keygrip key. This signature key is used to detect tampering the next time a cookie is received.

I saw that the signature is happening in the [https://www.npmjs.com/package/cookies](cookies module).  I looked and found that the cookies module uses the [https://www.npmjs.com/package/keygrip](keygrip) module.

The keygrip module is using HMAC which, even with SHA1, is still cryptographically secure.  The `keys` documentation does specify that you can configure the hashing algorithm with a Keygrip instance:

> The list of keys to use to sign & verify cookie values, or a configured Keygrip instance. Set cookies are always signed with keys[0], while the other keys are valid for verification, allowing for key rotation. If a Keygrip instance is provided, it can be used to change signature parameters like the algorithm of the signature.

But, I do feel like it would be worthwhile changing this line:
> with a 27-byte url-safe base64 SHA1 value representing the hash of cookie-name=cookie-value

to something similar to this:
> with a 27-byte url-safe base64 SHA1 value representing the HMAC of cookie-name=cookie-value

It's possible most people assume this is an HMAC, so if that's the case, please disregard.  But, if there are others like me, it could save them some time researching.

Thanks for your thoughts!!

**Comment by aequasi** [comment]
Documentation also mentions that `signed` is false by default, but [the code](https://github.com/expressjs/cookie-session/blob/master/index.js#L54) defaults it to true

**Comment by aequasi** [comment]
https://www.npmjs.com/package/cookie-session

Only seems to show it here. Its correct in github.

**Comment by dougwilson** [comment]
Hi @aequasi , sorry I let this drop off. The content there was just copy-and-pasted from the `cookies` module. What I did here to help address was just to remove all the details and let folks refer to the source of the information (`cookies`) module instead of keeping duplicate information all over the place that will get out-of-sync. That should at least address this specific issue about the `cookie-session` readme being confusing about the signature. Especially since the user can change the hash algo, so documenting it as specifically SHA1 is also confusing.
