### ISSUE TITLE
Cannot destroy session when secure is true

### ISSUE THREAD

**Issue by MatthewRandle** [expressjs/cookie-session#129]
With secure off all is working well, when I destroy the session the cookies are removed but with it set to true the cookies remain.

**Comment by dougwilson** [comment]
Hi @MatthewRandle thanks for the report. I tried on my machine with a simple demo and wasn't able to reproduce the issue. Can you help provide the following information so I can check it out?

1. Version of this module you're using
2. Version of Node.js
3. Complete code that I can run that demonstrates the issue
4. Instructions for how to reproduce with the above code.

Thank you!

**Comment by dougwilson** [comment]
Closing due to no response.
