### ISSUE TITLE
NPM example is confusing

### ISSUE THREAD

**Issue by jaschaio** [expressjs/cookie-session#130]
I tried creating a pull request for this, but it looks like the [readme on npm](https://www.npmjs.com/package/cookie-session) is different to the readme in this repo so a pull request doesn't work.

On example you still use the old example described in #125:

```
app.use(function (req, res, next) {
  var n = req.session.views || 0
  req.session.views = n++
  res.end(n + ' views')
})
```

One would expect the counter to increase on every pageload, but it doesn't because of calling `n++` instead of `++n`.

[This was corrected in the git readme but apparently not on npm.](https://github.com/expressjs/cookie-session/commit/3311d811a69817344a86d838a4c529bc22f31474)

**Comment by dougwilson** [comment]
When I asked npm they said it was an issue on their side and would correct the README. AFAIK I'm not sure how to fix it, unless you have some steps I can do to correct it myself? I have tried publishing with the updated README but it was still the same, which is why I opened the issue with NPM.

**Comment by dougwilson** [comment]
Since that commit in Aug 2015, I have published 10 more times.

**Comment by jaschaio** [comment]
Thanks for letting me know, I didn't know that you were aware of the issue. Unfortunately I don't have any experience with npm so not sure how to fix this. I guess I will stop trusting npm readme's for now 😂
