### ISSUE TITLE
Secure cookie over proxy

### ISSUE THREAD

**Issue by abhishekhingu** [expressjs/cookie-session#134]
Hi My application server through below channel
                                                                                                        (http-proxy)
LB(HTTPS)--> IIS(HTTP)(Reverse Proxy)--->(ExpressJS App)------------>(Express API)

When I generate unsecure httponly cookie session then cookie information pass to client. but when I set secure: true  in configuration option session cookie information won't sent to client.

Please help me to resolve this issue.

**Comment by dougwilson** [comment]
Hi @abhishekhingu sorry you're having trouble. Did you follow the documentation on setting up Express behind proxies yet? If so, can you show what you've already done?

**Comment by abhishekhingu** [comment]
Hi dougwilson,

As I mentioned in the above post IIS Reverse proxy pointing to ExpressJS App that serves Angular app content and host proxy for Express API used to fetch resources for Angular App. high-level code for this proxy looks like below.
`const express = require('express');
const path = require('path');
const bodyParser = require('body-parser');
const httpProxy = require('http-proxy');
const config = require("./config");
const backend = config.backend; // Express API
const port = process.env.PORT || 4203;
const apiProxy = httpProxy.createProxyServer();
const app = express();

app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());

app.use('/', express.static(path.join(__dirname, './dist')));

app.all("/api/*",function(req, res, next) {
    apiProxy.web(req, res, {target: backend}, function(e) { console.warn("http-proxy exception:",e); });
});

app.get('*', function(req, res) {
    res.sendFile(path.join(__dirname, '/dist/index.html'));
});
apiProxy.on('proxyReq', (proxyReq, req) => {
        if (req.body) {
            const bodyData = JSON.stringify(req.body);
            proxyReq.setHeader('Content-Type','application/json');
            proxyReq.setHeader('Content-Length', Buffer.byteLength(bodyData));
            proxyReq.write(bodyData);
        }
    });
app.listen(port, 'localhost', function(err) {
    if (err) {
      console.log(err);
      return;
    }
    console.log('Listening at http://localhost:'+port);
  });`

**Comment by dougwilson** [comment]
So it doesn't look like you set the trust proxy setting in express to anything yet in your example.

**Comment by mrmartineau** [comment]
adding the below or similar *should* fix the issue:

```js
.set('trust proxy', 1)
```

See more docs here: http://expressjs.com/en/4x/api.html#trust.proxy.options.table
