### ISSUE TITLE
Please publish a new 2.x version

### ISSUE THREAD

**Issue by mariusa** [expressjs/cookie-session#135]
2.0.0-beta.3 hasn't been updated in 2 years:
https://www.npmjs.com/package/cookie-session 

Would you please publish a new version (2.0.0 final or beta4), so we can take advantage of cookie 0.8 dependency?

Thanks

**Comment by dougwilson** [comment]
Hi @mariusa sorry about that. I wouldn't recommend running beta versions in any critical applications, so I was under the assumption I could attend to some more pressing issues before rolling the next set of changes to the 2.0 beta.

That said, I will be publishing soon an rc.0 with the final changes based on feedback and then promoting to a stable 2.0 coming after that. The rc.0 will include an updated cookies.

**Comment by mariusa** [comment]
Thanks!

**Comment by dougwilson** [comment]
2.0.0-rc.1 is published now. Please test throughly if you're using it. The plan is to convert it as-is to 2.0.0 if no one reports anything show stopping in a month.

**Comment by mariusa** [comment]
Hey Douglas, 2.0.0-rc.1 has been working great! How about making it 2.0.0 ? Thanks

**Comment by mariusa** [comment]
Hi @dougwilson would you please consider publishing as 2.0? We've been using it for 1 yr.
