### ISSUE TITLE
Missing an encryption

### ISSUE THREAD

**Issue by Fellach** [expressjs/cookie-session#136]
Hi

I have a dockerized project with 
```
node: 13.10.1
cookie-session: 2.0.0-beta.3
```
where I've configured your lib as follows:
```js
const app = express();
app.set('trust proxy', 1);
const sessionParser = session({
  name: 'session',
  keys: [
    'some-secret',
    '123-96-long-def'
  ],
  maxAge: 86400000
})
app.use(sessionParser);
```

Why I'm seeing on client side the cookie encoded base64 only which can be easily decoded? I thought providing the keys guaranties that the cookie will be encrypted. Am I missing something?

**Comment by dougwilson** [comment]
This module does not provide encryption, just signature. Nothing about it providing encryption is in the readme :)

We had a feature request issue open, but no pull request showed in many year, so closed as stale. If you would like to make a pull request implementing encryption, it would be welcome
