### ISSUE TITLE
.isChanged, .isPopulated always return undefined

### ISSUE THREAD

**Issue by mananamenos** [expressjs/cookie-session#137]
I have tried to use `isChanged` or `isPopulated` but it always return undefined value. They are supposed to be `req.session` properties, so i call them `req.session.isChanged` but as i've said, i get undefined always. Is this a known issue? Does it only happen to me?
thanks

**Comment by mananamenos** [comment]
This is so weird, i've seen the `isChanged` and `isPopulated` props in index.js here in master branch of this repo. However, i've navigated now to my node_modules/cookie-session (version ^1.4.0) and the code is different than the one i see in master branch. In my node_modules/cookie-session index.js I see function `changed` instead of a property `isChanged`? 
Could someone explain me what im missing?
Thanks

**Comment by dougwilson** [comment]
The master branch is the 2.0 RC

**Comment by mananamenos** [comment]
Hi, I see that. However, the code `npm install cookie-session` installs is not the same as the code in master, or 2.0 RC release. The code downloaded from npm does not have `isChanged`. Then I still don't understand then how the package distribution works.
While does the line `"cookie-session": "^1.4.0",` doesn't download the same code as in here/github?

**Comment by dougwilson** [comment]
The default version you get with npm is the documentation provided on npm: https://www.npmjs.com/package/cookie-session

You can use npm to install the RC specifically if you like like to try it out :)

**Comment by dougwilson** [comment]
Here is 1.4.0 version on githib: https://github.com/expressjs/cookie-session/tree/1.4.0

**Comment by mananamenos** [comment]
oh, i see now. sorry! then npm has a quite old version :) thank you

**Comment by dougwilson** [comment]
The npm version (1.4.0) is from January, the same time that the 2.0 RC version is from :)
