### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by bahmanbs** [expressjs/cookie-session#139]
hi there

cookie session is not working when using @types/cookie-session in typescript because of cookieSessionObject interface

the issue is with this:

    interface CookieSessionObject {
        /**
         * Is true if the session has been changed during the request.
         */
        isChanged: boolean;

        /**
         * Is true if the session is new.
         */
        isNew: boolean;

        /**
         * Determine if the session has been populated with data or is empty.
         */
        isPopulated: boolean;

        [propertyName: string]: any;
    } 

i think isPopulated, isNew and isChanged must be optional in interface.

**Comment by dougwilson** [comment]
Issues for any npm module that starts with `@types/` should be filed at https://github.com/DefinitelyTyped/DefinitelyTyped
