### ISSUE TITLE
[Documentation] What's the difference between req.login() by passport.js and req.session.save()?

### ISSUE THREAD

**Issue by mishuvs** [expressjs/cookie-session#140]
I am beginning to learn Passport.js and Cookie-session with a simple authentication project. I felt that I could not find clear documentation about how to use req.login() and req.session.save() together.

There are 2 unanswered StackOverflow questions which relate a lot to my problem:

1. https://stackoverflow.com/questions/62894933/why-use-cookie-session-in-addition-to-passport-js
2. https://stackoverflow.com/questions/62896503/how-to-initiate-session-on-signup-with-cookie-session-and-passport-js

Would be great if this could be clarified. Thanks

**Comment by dougwilson** [comment]
This question would be more appropriate to ask on the passport.js project.
