### ISSUE TITLE
iframe session issue

### ISSUE THREAD

**Issue by jadbox** [expressjs/cookie-session#145]
I have an iframe page that is coming from an Express server using cookie-session. Outside of the iframe, the session data is saved and restored between page refreshes. However, in an iFrame the cookie-session loses its data. 

```
app.use(cookieSession({
  name: 'session',
  secret: COOKIE_SECRET,
  sameSite: false
}))
```

**Comment by dougwilson** [comment]
This module can only restore the session if the web browser sends the cookie in the request. What web browser is being used in your case?

**Comment by Kresten** [comment]
I have the same problem.
I use Chrome 86 and have not enabled "Block third party settings" in settings. 
Since it works without the iframe, it seems that Chrome does not save the cookie when it is from an iframe

**Comment by dougwilson** [comment]
Closing as I never got a response from OP
