### ISSUE TITLE
Can the cookie be used in 2 events?

### ISSUE THREAD

**Issue by TheFinality** [expressjs/cookie-session#146]
Im using express, I have a /dashboard and /. When I make a cookie in the '/', and I try to get the cookie in the '/dashboard', it returns null. Any help?

**Comment by Lakhan-Nad** [comment]
Hello @F1R3L1GHT. I dont think this library parses the cookies. So I dont think you can access cookie in /dashboard or even in /. And cookie header available in both the routes. If you want to access req.cookie you might look into ``` cookie-parser ```
Hope it helps.
