### ISSUE TITLE
Unable to maintain session between ports.

### ISSUE THREAD

**Issue by chopfitzroy** [expressjs/cookie-session#147]
Hey there 👋,

I have setup a custom local domain as I wasn't sure if `localhost` could be causing this issue, it is something like `app-name.local`.

I have an Express API that I am running on port `8080` so I am hitting it using `app-name.local:8080/endpoint`.

I have a React UI running on port `3000` which I am accessing via `app-name.local:3000`.

I have an endpoint in the API that redirects off to a Github page for some oauth authorization, when this endpoint is hit I set a field in the session called `origin` which essentially says which UI the request came from (there are two). Once Github authorizes it redirects back to another API endpoint in this endpoint I set a `token` field in the session based on the parameters Github returns and then use the `origin` value to redirect back to the correct UI, this all works great and I can log the `token` out in the API.

The problem is when I redirect back to the UI (on port `3000`) and try to make subsequent requests from here the token is now undefined (a new session appears to be being created), interestingly if I just go to `app-name.local:8080/` it shows the `cannot GET` message from Express as I have no views but the token is logged again on the API, so essentially when I hit `app-name.local:8080` in the browser directly it gets the right session but when I make requests from `app-name.local:3000` it is using a new session?

Am I misunderstanding sessions? Essentially I thought anything under `app-name.local` which use the same session (or even `sub.app-name.local`?

I don't know if it helps but here is the redirect (to Github) endpoint:

```js
const githubOauthRedirect = async (request, response) => {
    const { query, session, oauthApp } = request;
    const { state, scopes, origin, allowSignup, redirectUrl } = query;

    // @NOTE we could use `redirectUrl` but there are a whole lot of domain rules...
    // - This gives us full control and makes the query params a lot cleaner
    if (!origin) {
        response.status(403).json({ message: `Error processing 'githubOauthRedirect', missing parameter: 'origin'` })
        return;
    }

    session.origin = origin;

    const url = oauthApp.getAuthorizationUrl({
        state,
        allowSignup,
        redirectUrl,
        scopes: scopes?.split(","),
    });

    response.redirect(302, url);
    return;
};

export default githubOauthRedirect;
```

And here is the receive and redirect (back to UI) endpoint:

```js
const githubOauthReceive = async (request, response) => {
    const { query, session, oauthApp } = request;
    const { code, state } = query;

    const url = getRedirectUrl(session.origin);

    const { token } = await oauthApp.createToken({
        code,
        state
    });

    session.token = token;

    response.redirect(302, url);
    return;
};

export default githubOauthReceive;
```

**Comment by chopfitzroy** [comment]
I also tried disabling `secure` and adding `app-name.local` as the `domain` in the `cookie-session` options.

**Comment by chopfitzroy** [comment]
I tried this with `express-session` as well just to see if it was related to the client, experienced exactly the same issue.

**Comment by chopfitzroy** [comment]
Okay so I have debugged this even further, I changed back to `localhost` as I am pretty sure the issue is not domain name related.

When I click on the link `localhost:8080/githubOauthRedirect` a new session is created.

I can log this session out and it's `isNew` is `true` once and then `false` before it redirects back to `localhost:3000`.

But when I get back to `localhost:3000` and try to make a subsequent `POST` request I get `isNew` as `true` which would indicate the UI is creating a new session even though I previously clicked through to `localhost:8080/githubOauthRedirect` from the UI and can confirm a session was created with a valid `token`.

From what I can see every time I hit the `localhost:8080/githubOauthRedirect` endpoint it maintains it's original session once it is created, but all requests from the UI are being treated as new sessions, this is based on the fact that the logger spits out the same `token` and `isNew` as false, additionally if I go directly to `localhost:8080/` in the browser my logger shows the existing session with it's `token`.

Interestingly on inspecting the Cookies in my devtools they seem to be the same for both port numbers?

![image](https://user-images.githubusercontent.com/2978850/102705690-1d3bb000-42ef-11eb-936f-4f4179504d85.png)

And

![image](https://user-images.githubusercontent.com/2978850/102705694-22006400-42ef-11eb-8afe-cbffa2ae4644.png)

I think this might be to do with the `credentials` I am passing through in the fetch request from the UI, or possibly the `sameSite` setting with the `cookie-session` or a combination of they two, but so far everything has rendered the same results.

**Comment by Xiangmingchen** [comment]
I had a similar issue. My browser was not saving my request cookies. I believe the browser considers different ports on local hosts to be different domains. This article helped me overcome me issue: https://voonminghann.medium.com/samesite-cookie-for-localhost-development-28e4d9499baf
