### ISSUE TITLE
Can cookie-session persist? 

### ISSUE THREAD

**Issue by bettafish15** [expressjs/cookie-session#148]
I know this is not the good place to ask questions but this really bugs me . I cant figure out how to make cookie-session persists
i set cookie-session like this:

```js
var expiryDate = new Date(Date.now() + 24 * 60 * 60 * 1000) // 1 day
app.use(cookieSession({
  name: 'sessId',
  keys: ['test1', 'test2'],
  cookie: {
    secure: true,
    httpOnly: true,
    domain: constData.DOMAIN,
    path: '/api',
    expires: expiryDate,
    maxAge: 24 * 60 * 60 * 1000
  }
}))
```
then i set the session using:
```js
req.session.user = 'blah';
```

after i close chrome browser and open up again i tried to access the session but it's appeared null. According to my understanding i can persist session if i put expires options when creating the cookie-session middleware am i right?

**Comment by bettafish15** [comment]
So because hours of coding makes me dizzy and cant even see that i am passing wrong parameters into cookie-session. It should be
```js
var expiryDate = new Date(Date.now() + 24 * 60 * 60 * 1000) // 1 day
app.use(cookieSession({
  name: 'sessId',
  keys: ['test1', 'test2'],
  secure: true,
  httpOnly: true,
  domain: constData.DOMAIN,
  path: '/api',
  expires: expiryDate,
  maxAge: 24 * 60 * 60 * 1000

}))
```

Sorry for wasting you guys time lmao

**Comment by richardscarrott** [comment]
@bettafish15 given you're passing an absolute date for the expiry does this mean if your server ran for more than a day the date would be in the past; does `expires` accept a fn to ensure it's a new instance for every request?

**Comment by richardscarrott** [comment]
Also, I'm guessing you got that incorrect snippet above from https://expressjs.com/en/advanced/best-practice-security.html#set-cookie-security-options?

**Comment by bettafish15** [comment]
> Also, I'm guessing you got that incorrect snippet above from https://expressjs.com/en/advanced/best-practice-security.html#set-cookie-security-options?

Yes you right. However that's not my question i am asking here. I dont think you should use expiryDate but use maxAge instead

**Comment by richardscarrott** [comment]
@bettafish15 yeh I ended up using `maxAge` too as it turns out it [sets `Expires`](https://github.com/pillarjs/cookies/blob/0.8.0/index.js#L169) under the hood rather than [`Max-Age`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#permanent_cookie) anyway 👍
