### ISSUE TITLE
How to change the maxage of a session for a specific user?

### ISSUE THREAD

**Issue by NotQuite** [expressjs/cookie-session#15]
In express3.x this was possible using `req.session.cookie.maxAge`.
However it seems that req.session.cookie is undefined. So is it possible to change the properties of the cookie without changing them globally?

**Comment by dougwilson** [comment]
Hi! Sorry this module has been sitting around for so long! I have added how you can do this with `req.sessionOptions.maxAge` in the readme, which has been available for the lifetime of this module, but just undocumented.

**Comment by dougwilson** [comment]
Eh, nevermind. That doesn't work right. This module needs a serious overhaul :)

**Comment by dougwilson** [comment]
For now, with version 1.2.0, the solution would be as follows if you want a sticky maxAge:
```js
app.use(cookieSession())
app.use(function (req, res, next) {
  req.sessionOptions = req.session.maxAge || req.sessionOptions
})
```
