### ISSUE TITLE
Encryption doesn't work

### ISSUE THREAD

**Issue by asmyshlyaev177** [expressjs/cookie-session#150]
Encryption with secret or with keys doesn't works.
Cookie in both cases can be simply decoded by 
```
atob('cookie_string-sdfsdf')
```

Config: 
```
const cookieOptions = {
  domain: config.domain,
  httpOnly: true,
  name: 'session',
  sameSite: 'lax',
  //secret
  keys: new Keygrip([secret], 'SHA384', 'base64'),
  signed: true,
  secure: false,
  secureProxy: config.isProduction,
}
app.use(cookieSession(cookieOptions))
```

**Comment by blakeembrey** [comment]
@asmyshlyaev177 This package doesn’t do encryption, when you provide `keys` it’s signing the value so you can verify that your service was the one to issue it.

**Comment by dougwilson** [comment]
And the docs are clear it is for signing the cookie value; there is no mention of encryption in the docs.
