### ISSUE TITLE
sameSite/secure settings not accepted by chrome

### ISSUE THREAD

**Issue by mark-night** [expressjs/cookie-session#151]
I have set cookie-session option to 
```
{
  /*other options*/
  sameSite: 'none', // to allow cross-site cookie
  secure: true,
  httpOnly: true,
}
```
Server is running on https://localhost:4000 (https setup using self-signed certificate). Everything works fine except that Chrome seems not taking the `sameSite` and `secure` settings as the `SameSite=None; Secure` attributes, it simply logs the cookie as  "SameSite attribute not set or invalid".

What might be causing this?

**Comment by dougwilson** [comment]
AFAIK Chrome will reject samesite=none if you have a certificate error. But ultimately, unless you are saying that tgis module is not producing the right http header, it may be best to ask on a forum with Chrome experts who would know for sure.

**Comment by mark-night** [comment]
@dougwilson How do I check if http header is correctly produced? And, how do I inspect if there is any error with the self-signed certificate?

The certificate is generated and signed via the [mkcert](https://github.com/FiloSottile/mkcert) tool, pretty simple and straight forward. I then created the server with node js `https` and `express` module serving the cert/key generated by `mkcert`. Browsers (Chrome, Firefox and Safari) don't report any error about the certificate, they all show the lock icon in address bar.

To the cookie error, the cookie was blocked by Chrome, and clearly that, Chrome believe Security and SameSite attributes were not set correctly (see the attached screenshot).
![Screen Shot 2021-03-08 at 14 40 25](https://user-images.githubusercontent.com/48889700/110392639-1aaf4380-801e-11eb-948c-cac0ab8ebfde.jpg)

As with Safari, it thinks Secure was set (Chrome doesn't), and it doesn't recognize SameSite neither. 
![Screen Shot 2021-03-08 at 14 52 32](https://user-images.githubusercontent.com/48889700/110392753-4a5e4b80-801e-11eb-94ae-48a7d23158fe.jpg)

Firefox seems accepting cookie without any issue, however, I couldn't see the cookie in cookies tab, although I can detect that the cookie is working...

**Comment by mark-night** [comment]
Never mind, I'm an idiot. The issue was about a previous incorrect cookie. I just had to refresh the cookie, and now everything is OK. Sorry.
