### ISSUE TITLE
Documentation don't match between npm and github

### ISSUE THREAD

**Issue by Etherum7** [expressjs/cookie-session#152]
In NPM

<img width="554" alt="Screenshot 2021-05-29 at 1 20 23 PM" src="https://user-images.githubusercontent.com/58840954/120062600-b5994600-c080-11eb-8bcb-304e7190cfe0.png">

While in github and code editors

<img width="520" alt="Screenshot 2021-05-29 at 1 21 55 PM" src="https://user-images.githubusercontent.com/58840954/120062651-e5e0e480-c080-11eb-972a-b3061eb95366.png">

<img width="518" alt="Screenshot 2021-05-29 at 1 22 40 PM" src="https://user-images.githubusercontent.com/58840954/120062667-fc873b80-c080-11eb-830a-800219a735c0.png">

**Comment by Etherum7** [comment]
Thanks for creating such a useful library 🙏

**Comment by dougwilson** [comment]
Unfortunately npm can only show one version of the readme and it shows 1.x stable and not the 2.0 rc.

**Comment by dougwilson** [comment]
Sorry, to clarify it can only show one readme as the "main" one. If you click on the versions link on npm and then check the version of this module you installed, you can view that version's readme on npm.
