### ISSUE TITLE
Update dependency from debug@3.2.6 to debug@3.2.7

### ISSUE THREAD

**Issue by Ylianst** [expressjs/cookie-session#155]
Currently, cookie-session has a dependency on debug@3.2.6 which has a reported vulnerability.

```
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
```

Can a new release be made on NPM with the dependency changed to 3.2.7? Thanks.

**Comment by dougwilson** [comment]
Ah, I believe you are referring to the unreleased 2.x line of this module. Apparently I didn't get any alert for it. I'll bump that and publish as the actual 2.0 instead of a new rc.

**Comment by dougwilson** [comment]
This change landed and will be in the next release.
