### ISSUE TITLE
How to use cookie-session with React Native apps?

### ISSUE THREAD

**Issue by saikarthikp9** [expressjs/cookie-session#156]
I am trying to use this package with a react native app but it is not working. Does anybody use this with their react native apps?
I am specifically using Axios.

**Comment by dougwilson** [comment]
Hello, sorry you are having trouble. It seems like the folks here don't have an answer for your specific question. You may try StackOverflow which contains more folks from different background, increasing your chance of finding a person who knows this module and React Native.
