### ISSUE TITLE
browser not saving cookie

### ISSUE THREAD

**Issue by metrocoding** [expressjs/cookie-session#157]
hello, I use cookie session this is my code in my browser I see the cookie in response in the network tab but it doesn't set in storage in firefox chrome safari.
this is my code:

```
app.set("trust proxy", true);
app.use(cookieSession({ signed: false, secure: false }));
```

this is how I set cookie:
`req.session = { jwt: userJwt };`

cookie in response:
<img width="1434" alt="Screen Shot 2021-11-06 at 2 36 46 AM" src="https://user-images.githubusercontent.com/46874334/140587872-438edd57-d66d-453d-9444-1513521c057c.png">
e

nothing in storage:
<img width="1434" alt="Screen Shot 2021-11-06 at 2 37 12 AM" src="https://user-images.githubusercontent.com/46874334/140587902-4579b1d8-5915-480b-8354-f05383f5a7d3.png">

**Comment by dougwilson** [comment]
Hello, sorry you are having trouble. Unless there is something missing, I don't see anything wrong with the cookie response you are displaying. It's possible this an issue with the web browser and would need to be opened on their issue tracker unless you think there is something missing from the cookie response?

**Comment by metrocoding** [comment]
thanks, I will do that.

**Comment by dougwilson** [comment]
Closing stale issue.
