### ISSUE TITLE
Is there a risk when someone modifies the userId in the cookie?

### ISSUE THREAD

**Issue by YogeshUmeshVaity** [expressjs/cookie-session#158]
I'm using this package to identify the users by storing a `userId` in the cookies. So if someone tries to set random `userId`s as cookie data in their browser, will they be able to convince my server that they are a user while they actually are not?

Does this package have some sort of mechanism for dealing with this kind of risk?

**Comment by dougwilson** [comment]
As long as you provide a secret and/or keys the user cannot change the contents without knowing that information. That is the protection mechanism thia module provides against tampering.

**Comment by YogeshUmeshVaity** [comment]
@dougwilson Thank you!
