### ISSUE TITLE
Cookie lost on mobile?

### ISSUE THREAD

**Issue by gom59** [expressjs/cookie-session#159]
This might be a non-issue, and more a lack of knowledge on my part concerning cookies.
I have deployed a small site, which users mostly open on mobiles. And it seems to be that some users loose their session cookie very quickly (within minutes). 
I have not collected enough data for now, and cannot say precisely which browsers are affected, although user who reported this directly to me were iPhone users.
Am I missing something, should I specify a certain option to make sure the cookie is preserved whatever the user does?

**Comment by dougwilson** [comment]
Hi that is very interesting. AFAIK the only mechanisms cookies are for preserving them in the `max-age` attribute. If there is something that should be added to thia module though, please let us know and this can be reopened.
