### ISSUE TITLE
Default cookie name doesn't satisfy RFC6265

### ISSUE THREAD

**Issue by guersam** [expressjs/cookie-session#16]
The default cookie name [`express:sess`](https://github.com/expressjs/cookie-session/blob/master/index.js#L22) contains `:`, which is not a valid token character in accordance with [RFC6265](https://tools.ietf.org/html/rfc6265#section-4.1.1) and [RFC2616](https://tools.ietf.org/html/rfc2616#section-2.2). Although most web browsers and servers allow this, it causes problems in some more strict environment such as [spray](http://spray.io).

Would you consider remaining it? If so, should we take backward compatibility into account?

p.s. I posted the same issue as koajs/session#28.

**Comment by anextro** [comment]
Has this problem been solved.?

**Comment by dougwilson** [comment]
@anextro no, not until the next major release. You can always just use a different cookie name from the default for your app in the meantime.
