### ISSUE TITLE
The same session id for all users

### ISSUE THREAD

**Issue by minhsiro** [expressjs/cookie-session#163]
How do I generate different sessionID for different users?
Right now all users have the same sessionID no matter how many times I try logging in.
And also, after the session expired, cookieSession generates the same sessionID again?
Please help!

```
const fs = require('fs');
const path = require('path');
const https = require('https');
const express = require('express');
const helmet = require('helmet');
const passport = require('passport');
const { Strategy: GoogleStrategy } = require('passport-google-oauth20');
const cookieSession = require('cookie-session');
const cookieParser = require('cookie-parser');

require('dotenv').config();

const PORT = process.env.PORT || 3000;

const config = {
  CLIENT_ID: process.env.CLIENT_ID,
  CLIENT_SECRET: process.env.CLIENT_SECRET,
  COOKIE_KEY_1: process.env.COOKIE_KEY_1,
  COOKIE_KEY_2: process.env.COOKIE_KEY_2,
};

const AUTH_OPTIONS = {
  callbackURL: '/auth/google/callback',
  clientID: config.CLIENT_ID,
  clientSecret: config.CLIENT_SECRET,
};

const verifyCallback = (accessToken, refreshToken, profile, done) => {
  // console.log('profile: ', profile);
  done(null, profile); // email & profile in scope
  // this will return the flow to passport.authenticate()
};

passport.use('google', new GoogleStrategy(AUTH_OPTIONS, verifyCallback));

passport.serializeUser((user, done) => {
  // set cookie with user.id
  done(null, user.id);
  // whatever passed into the done function will be set in the req.session.passport.user
  // & req.user
});

// read the session from the cookie
passport.deserializeUser((id, done) => {
  done(null, id);
});

// app.use() takes in a request handler
const app = express();

app.use(helmet());

app.use(cookieParser());
app.use(express.json());

app.use(
  cookieSession({
    name: 'session',
    maxAge: 60 * 1000,
    keys: [config.COOKIE_KEY_1, config.COOKIE_KEY_2],
  })
);

// this is invoked on every request
app.use(passport.initialize());
app.use(passport.session());

const checkLoggedIn = (req, res, next) => {
  const isLoggedIn = req.isAuthenticated() && req.user;
  if (!isLoggedIn) {
    return res.status(401).json({
      error: 'you muse log in!',
    });
  }
  next();
};

app.use(express.static('public'));

app.get(
  '/auth/google',
  passport.authenticate('google', {
    scope: ['email'],
    accessType: 'offline', // this is for refresh token. without this line: refreshToken will be undefined.
  })
);

app.get(
  '/auth/google/callback',
  passport.authenticate('google', {
    failureRedirect: '/failure',
    successRedirect: '/',
    session: true, // true by default
  }),
  (req, res) => {
    console.log('google called us back');
  }
);

app.get('/failure', (req, res) => {
  return res.send('failed to login');
});

app.get('/auth/logout', (req, res) => {
  req.logout();
  return res.redirect('/');
});

app.get('/secret', checkLoggedIn, (req, res) => {
  return res.send('your personal secret is 42.');
});

app.get('/*', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

const server = https.createServer(
  {
    key: fs.readFileSync('key.pem'),
    cert: fs.readFileSync('cert.pem'),
  },
  app
);

server.listen(PORT, () => {
  console.log(`listening on PORT:${PORT}`);
});


```

**Comment by dougwilson** [comment]
Hello, and sorry you are having trouble. This module does not generate any type of session ID, so it is unclear what you mean by that. Can you show an example of what you are referring to as the session ID?

**Comment by minhsiro** [comment]
Hi, thank you for getting back. I just updated the code above. I use cookie-session with passport. The problem is that after the cookie session expire and I relog in, it generates the same value for the next session cookie.

**Comment by dougwilson** [comment]
This module does not generate any type of session ID, so it is unclear what you mean by that. Can you show an example of what you are referring to as the session ID?

**Comment by minhsiro** [comment]
The code above set a cookie in the browser every time I sign in with google. But after the cookie expired & I sign in again, it set the same value as before for the cookie every time. How do I generate different values for my cookies every time I log in?

**Comment by dougwilson** [comment]
Thia module doesn't use a session ID, as outlined in the readme. The value is whatever the contents you are putting in `req.session`. If you always put the same value, you'll always have the same value in the cookie too...

**Comment by dougwilson** [comment]
Looking at the code, the comments seem to say that you are storing the user ID in the session data. So if in your example both log ins are the same user, the value of the cookie is expected to be the same, if that is the same between bot log ins and you are not storing anything else in it.

**Comment by minhsiro** [comment]
Well yes, but it only store a single user ID in the session data, what if I have multiple users, what can I do? Like I have 10 users logging into my application, the req.session only store the latest user. Does cookie-session do anything about it?

**Comment by dougwilson** [comment]
The cookie value will have whatever you put in `req.session`. If you put different values for different users, then yes, the cookie values will be different between users.

**Comment by minhsiro** [comment]
"but it only store a single user ID in the session data". The req.session can only have 1 value at a time.

**Comment by dougwilson** [comment]
> The req.session can only have 1 value at a time.

I'm not sure what this means. You can store as many key-value pairs in the `req.session` object that you want. This module will take anything you put in `req.session` and saves it. For example, you can do `req.session.user = 'foo'` and `req.session.token = 'bar'` and now your session consists of `{"user":"foo","token":"bar"}`.

**Comment by AndresRodH** [comment]
> Well yes, but it only store a single user ID in the session data, what if I have multiple users, what can I do? Like I have 10 users logging into my application, the req.session only store the latest user. Does cookie-session do anything about it?

I think there's a misconception on what this package does. It will use a cookie to store the user's session. This cookie lives in the user's browser.

Your session object is not global and doesn't get reused by requests coming from different users.
