### ISSUE TITLE
How to: Generate session for testing

### ISSUE THREAD

**Issue by OrestisNer** [expressjs/cookie-session#167]
Hey there.

I am trying to test an endpoint that requires a `cookie` to authenticate.
Currently, to generate a session (`express:sess: ....`) I use an existing `login` endpoint and get the `Set-Cookie` value from the response.

```js
export const login = async (user) => {
    const loginPath = `/api/v1/auth/signin`;
    const { email, password } = user;
    const response = await request(app)
        .post(loginPath)
        .send({
            email,
            password
        })
        .expect(200);

    return response.get("Set-Cookie");
};
```

I was wondering if there is a way to generate this session (`express:sess: ....`) without calling this endpoint. 
The session object data are `{ accessToken: string, refreshToken: string}`.

So, the end result that I would prefer is 

```js
// session doesn't exist. It's only for the sake of the example
import { Session } from "cookie-session";

export const login = () => {
    const sessionData = { accessToken: "..", refreshToken: ".."};
    // method that generates the session 
    return Session.create(sessionData); // return (`express:sess: ....`)
};
```
Do you know if this is possible?
And if it's not possible with `cookie-session` do you know any other package that is more flexible?

**Comment by dougwilson** [comment]
Is your `express:sess` from this module or from `express-session` module? If so, then there is no way to generate it outside that module because the data is stored server side. If it is actually from this module, can you show what you're currently doing in the endpoint and what the set-cookie content looks like currently?

**Comment by OrestisNer** [comment]
I am using `cookie-session` and inside the `login` endpoint I set the `req.session` with the object `{ accessToken: string, refreshToken: string}`.

```
req.session = await getSessionTokens({ id, email }); // returns `{ accessToken: string, refreshToken: string}`.
``` 

The `Set-Cookie` header is `'express:sess=eyJh.....==; path=/; httponly'

**Comment by OrestisNer** [comment]
I found [this gist](https://gist.github.com/WaleedAshraf/4106be954bf522cf25bda3b59e2ea8a6) that was very helpful.
For my case the code was

```
import keygrip from "keygrip";

export const generateTestSession = async (user: UserI) => {
    const { id, email } = user;
    const sessionTokens = await getSessionTokens({ id, email }); // returns `{ accessToken: string, refreshToken: string}`.
    const cookie = Buffer.from(JSON.stringify(sessionTokens)).toString(
        "base64"
    );

    const kg = keygrip([env.COOKIE_SESSION_KEY]);
    const hash = kg.sign(`${env.COOKIE_SESSION_NAME}=${cookie}`);

    return [
        `${env.COOKIE_SESSION_NAME}=${cookie}; ${env.COOKIE_SESSION_NAME}.sig=${hash};`
    ];
};

```
