### ISSUE TITLE
Cannot set the .sig cookie's expiry

### ISSUE THREAD

**Issue by yawhide** [expressjs/cookie-session#21]
This may not be a bug, but just me not knowing what to do.

So I want to update my session cookie everytime my users to an api call and he/she has ticked the "remember me" checkbox on login. So far, I have been able to update the expiry on the express:sess cookie just fine. Now my issue is I cannot update the expiry of my express:sess.sig cookie. When my user quits his/her browser, the express:sess.sig cookie disappears and my user will no longer have a valid session (even though he/she still has the express:sess cookie)

Am I doing something fundamentally wrong here?

In your docs you say this: "Other options are passed to cookies.get() and cookies.set() allowing you to control security, domain, path, and signing among other settings."
Where do we actually change what cookies.set() does? Maybe its in cookies.set() where I should add 7 days to the expiry?

**Comment by alvarotrigo** [comment]
> using sessions isn't the way a "remember me" function works--it doesn't keep you logged in for longer, it just sets another secondary cookie with like you username in it.

Not quite sure about that. If you take the example of Gmail, it will log you in again when you open the browser next time. 
It doesn't say "Remember me" but instead it says "Stay signed in" but I think @yawhide was referring to this last option.

I also expected to find some similar behavior in this component so we could change the `maxAge` or set it for the 1st time dynamically in an attempt to create the "Stay signed in" feature.

**Comment by alvarotrigo** [comment]
Would it be possible to do something along these lines?

```javascript
app.use(function(req,res,next ){
  if(typeof req.session == 'undefined' || req.session.staySignedIn === 'undefined'){
    console.log("Remember me was NOT active!!!!".green);
    cookieSession({
      httpOnly: true,
      secure: false,
      secureProxy: true,
      keys: ['key1', 'key2']
    });
  }else{
      console.log("Remember me was active!!!!".green);
    cookieSession({
      httpOnly: true,
      secure: false,
      secureProxy: true,
      keys: ['key1', 'key2']
    });
  }
  next();
});
```
