### ISSUE TITLE
no longer a fork of from koajs/cookie-session

### ISSUE THREAD

**Issue by Fishrock123** [expressjs/cookie-session#24]
cc @dougwilson @jonathanong I emailed github staff and this is no longer a fork.

**Comment by q2dg** [comment]
Excuse me if it a offtopic, please, but...which relationship exists between this module and https://github.com/expressjs/session ? I mean...the latter supersedes the former, doesn't? If it does, why bothering maintaining this module? I'm surely wrong, but hence I ask. Thanks

**Comment by dougwilson** [comment]
This module stores the _contents of the session_ in a cookie, while express-session stores the contents of the session on the server.

**Comment by q2dg** [comment]
Oooh, I see...from express-session main page: "Session data is not saved in the cookie itself, just the session ID." Ok, ok.
Thanks a lot, @dougwilson (and sorry for the inconvenience, again!)

**Comment by dougwilson** [comment]
@q2dg it was no problem clearing that up for you :)
