### ISSUE TITLE
cookie-session seems to ignore the overwrite option

### ISSUE THREAD

**Issue by purple-panda** [expressjs/cookie-session#31]
I want my user's session cookie to be updated every time they interact with the site, but cookie-session will only update the cookie if the contents has changed. From the documentation it seems that the overwrite option is designed to allow the cookie to be updated which each request.

This would allow the us to set a semi-short expiration time and update it with every interaction without needing to change the contents of the cookie. The only work around I've been able to come with right now is to write another property containing a new Date() object with each request, but this feels very hack-y-ish to me. 

In the code, cookie-session reads in the overwrite option, but then just ignores it when deciding whether or not to right the cookie. The overwrite option seems to just be ignored in the code altogether. I guess it gets passed to the cookies module with all of the other options, but the behavior is ignored in the native session-cookie code.

**Comment by purple-panda** [comment]
It looks like PR #30 would solve this issue perfectly for me. I'll see if the author needs help with tests.

**Comment by dougwilson** [comment]
Closing in response to the investigation summarized at https://github.com/expressjs/cookie-session/pull/30#issuecomment-118393784
