### ISSUE TITLE
Count example in page is increasing by two.

### ISSUE THREAD

**Issue by anextro** [expressjs/cookie-session#32]
I tried to test the count example of this module and noticed that it is increasing by two.

I am testing on my local machine no nginx. 

It's almost as if my client machine is making a request twice behind the scenes.
What might be the issue?

EDIT: This is a copy of the http header that is sent to the client. Interesting that there are two Set-Cookie
```
HTTP/1.1 200 OK
Connection: keep-alive
Date: Tue, 14 Apr 2015 20:54:02 GMT
Set-Cookie: finda-sess=eyJjb3VudCI6MzN9; path=/; httponly
Set-Cookie: finda-sess.sig=g9IWmpQ9GvzHHQnDyTeOfAhauto; path=/; httponly
Transfer-Encoding: chunked
X-Powered-By: Express
```

**Comment by dougwilson** [comment]
Because the example is just `app.use`, it is very likely there is a second request (perhaps a favicon request or something)? Can you change
```js
app.use(function (req, res, next) {
  var n = req.session.views || 0
  req.session.views = ++n
  res.end(n + ' views')
})
```

to

```js
app.use(function (req, res, next) {
  console.log(req.method + ' ' + req.url)
  var n = req.session.views || 0
  req.session.views = ++n
  res.end(n + ' views')
})
```
and run it and paste here? I'm interested in what the second request is and will improve the example :)

**Comment by anextro** [comment]
And the bug|feature has vanished.

I agree with you that it is a favicon request. I happen to be using Live HTTP Headers, so previously it there was a favicon request but right now, it is not showing again.

So i'm guessing that i probably should have intercepted the favicon request with the serve-favicon middleware.

Thanks
