### ISSUE TITLE
The default cookie name is not compliant with RFC 6265

### ISSUE THREAD

**Issue by vschoettke** [expressjs/cookie-session#33]
RFC 6265 (http://tools.ietf.org/html/rfc6265#section-4.1.1) specifies the cookie name as token that is defined in RFC 2616 (http://tools.ietf.org/html/rfc2616#section-2.2) which specifies:

      token          = 1*<any CHAR except CTLs or separators>
       separators     = "(" | ")" | "<" | ">" | "@"
                      | "," | ";" | ":" | "\" | <">
                      | "/" | "[" | "]" | "?" | "="
                      | "{" | "}" | SP | HT

So just removing the colon from the default name would be fine.

**Comment by dougwilson** [comment]
Thanks! Though this is a duplicate of #16 and you can change the cookie name yourself (since it's configurable) for the time being.
