### ISSUE TITLE
The problem with example in README.md

### ISSUE THREAD

**Issue by isayme** [expressjs/cookie-session#34]
In example: [Simple view counter example](https://github.com/expressjs/cookie-session#simple-view-counter-example)

There a statement `req.session.views = n++`, since we set `req.session.views` with `n++`, the `req.session.views` will always be the old value of `n`, and we'll get `1 views` in every request.

we should change the statement to

    n++
    req.session.views = n

**Comment by gabeio** [comment]
true. n++ is post operation increase, after it sets req.session.views to n it then increases it... what would be easier is to just do:
```
req.session.views = n+1
```
OR
```
n = req.session.views+1 || 1
```

**Comment by isayme** [comment]
n = req.session.views || 1
    req.session.views = ++n;

replace `n++` with `++n` will be OK.

**Comment by dougwilson** [comment]
Thank you for the report!
