### ISSUE TITLE
Add warning if cookie size exceeds 4000 bytes

### ISSUE THREAD

**Issue by Resonance1584** [expressjs/cookie-session#35]
Currently if the cookie exceeds 4000 bytes it will fail to store in most modern browsers. This results in the user either repeatedly sending an older smaller session object, or having no session at all.

Cookie size limits are determined by the user-agent, so this should probably just be a console warning, not a failure or exception.

**Comment by dougwilson** [comment]
If the limit is determined by the user-agent, how do we know if we exceeded the limit?

**Comment by dougwilson** [comment]
We also cannot just `console.warn` in this code. For example, what if people want to disable that warning, or send that warning to a logging infrastructure? If there is a standard warning framework we can use? Or perhaps if we just use the `debug` module would that be good enough?

**Comment by Resonance1584** [comment]
Perhaps just a note in the readme is fine? I assume this is a rare bug - it should really be the responsibility of the user-agent to warn.

**Comment by dougwilson** [comment]
Gotcha. In order to add a note in the readme, the note needs to be very specific, like exactly what lengths for exactly which browsers? Can you put together a PR?
