### ISSUE TITLE
README: default value for "signed" option

### ISSUE THREAD

**Issue by ivan7237d** [expressjs/cookie-session#36]
It seems that the default value is actually `true`, but in the README it says `false`.

**Comment by dougwilson** [comment]
As far as I know it is false. Can you point to where in the code it defaults to true?

**Comment by dougwilson** [comment]
Oh, lol, I see it (tells you how much I look at this module :) ). I wonder where that text came from.

**Comment by dougwilson** [comment]
Nevermind, I was looking at the "signed" option. Yes, I'm not seeing the secure issue, so please point to where it is in the code :)

**Comment by ivan7237d** [comment]
Wait - I was speaking of the "signed" option, so I think the first impression was the right one )

**Comment by dougwilson** [comment]
lol, I totally can't read, apparently :) I agree with your assessment. Feel free to even make a PR, as I wont get to it for a while.
