### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by ForbesLindesay** [expressjs/cookie-session#41]
It looks like 2.x still isn't published.  I really want that change to include underscore prefixed properties.

**Comment by dougwilson** [comment]
It is not published because it's not completed yet. When all issues/PRs are resolved and closed, that's when 2.0 would be released.

**Comment by dougwilson** [comment]
Would you be interested if I published the current `master` branch to npm as `2.0.0-alpha.1`?

**Comment by ForbesLindesay** [comment]
That would be great.

**Comment by dougwilson** [comment]
@ForbesLindesay 2.0.0-alpha.1 has just been published to npm. Be sure to read the release notes at https://github.com/expressjs/cookie-session/releases/tag/2.0.0-alpha.1 before using :)
