### ISSUE TITLE
Capacity limit 

### ISSUE THREAD

**Issue by alvarotrigo** [expressjs/cookie-session#42]
I was reading about [the difference between using a Session and a Cookie Session](http://stackoverflow.com/questions/15744897/what-is-the-difference-between-session-and-cookiesession-middleware-in-conne) and it seems cookie sessions are only recommended if you want to have a small session data in it.

> The session middleware implements generic session functionality with in-memory storage by default. It allows you to specify other storage formats, though.

> The cookieSession middleware, on the other hand, implements cookie-backed storage (that is, the entire session is serialized to the cookie, rather than just a session key. It should really only be used when session data is going to stay relatively small.

I'm looking for a solution to implement sessions in the server side of a Windows machine and it seems [`express-session`](https://github.com/expressjs/session#compatible-session-stores) is not ideal for it as its not ready to work on production with the default storage module, and other modules like Redis won't be supported in Windows. Plus I'm just looking for a simple local solution. 

So I was just wondering what's the recommended data limit for which cookie-session should be used.

**Comment by dougwilson** [comment]
Should be about 4kb: #38
