### ISSUE TITLE
How to set the session options

### ISSUE THREAD

**Issue by alvarotrigo** [expressjs/cookie-session#45]
The [documentation](https://github.com/expressjs/cookie-session#cookie-options) doesn't seem to be very clear to me.
It says

> Other options are passed to cookies.get() and cookies.set() 

- What is `cookies` there? 
- Does it mean we have to use `set` to set the options we want?

I was trying to use cookieSession as [express-session](https://github.com/expressjs/session), but it seems that's not the way it works:

```javascript
var cookieSession = require('cookie-session');

app.use(cookieSession({
  maxAge: 20*60*1000, //20 mins
  httpOnly: true,
  secure: true,
  secureProxy: true,
  keys: ['key1', 'key2']
}));
```

**Comment by dougwilson** [comment]
Hi, I'll have to investigate to see what the answer is. If you can contribute a PR to enhance the documentation, that would be awesome :) This module has very poor documentation currently.

Also, which is the part that is not working? Are you getting a Set-Cookie response header? Did you set any value inside req.session?

**Comment by alvarotrigo** [comment]
It seems it is in fact initialized in that way. 
I was having troubles as I was overriding the `maxAge` value with an `undefined` value in a middleware. 

[This answer](http://stackoverflow.com/questions/24065054/how-to-pass-cookie-options-in-cookie-session-1-0-2) helped me to see that's the correct way of doing it.

In any case, I got confused exactly in the same way as the author of the question in stackoverflow:

> Of course, I have misinterpret this completely. This line: "Other options are passed to cookies.get() and cookies.set()... " tricked me into thinking that all other options has to be applied in another mystic way... but they are just passed on as you clarify =)
