### ISSUE TITLE
2.0.0-alpha.1 not in NPM

### ISSUE THREAD

**Issue by alvarotrigo** [expressjs/cookie-session#47]
The latest version is not actually in NPM.
Whenever I try to install the latest alpha version with npm the package.json file gets updated with `    "cookie-session": "^2.0.0-alpha.1"` but the code belongs to 1.2.0

> npm install cookie-session --save

Also, it would be nice to have a version number in the file. I had to use a code comparison tool to realise the version was not the correct one.

**Comment by dougwilson** [comment]
I'm not sure what you mean. Perhaps your npm cache has been corrupted?

Try running "npm cache clean && npm install cookie-session@2"

**Comment by dougwilson** [comment]
Unfortunately I cannot reproduce the issue you are seeing. I even looked at the literal bytes that are in the npm registry and in GitHub and they have the same MD5 hash:
```
$ npm info cookie-session@2.0.0-alpha.1 time.modified
2015-10-12T06:14:37.990Z

$ npm info cookie-session@2.0.0-alpha.1 dist.tarball
http://registry.npmjs.org/cookie-session/-/cookie-session-2.0.0-alpha.1.tgz

$ curl -s $(npm info cookie-session@2.0.0-alpha.1 dist.tarball) | tar -Ozx package/index.js  | md5sum
862484ec959fb35feb9fc38fd5515f96 *-

$ curl -s $(npm info cookie-session@2.0.0-alpha.1 dist.tarball) | tar -Ozx package/index.js | md5sum
862484ec959fb35feb9fc38fd5515f96 *-

$ curl -s https://raw.githubusercontent.com/expressjs/cookie-session/1.2.0/index.js | md5sum
5db6eeacf38dd2b93f2ae825384b1dba *-
```

If cleaning your cache does not work, you may need to open a support issue (https://github.com/npm/npm/issues) with NPM itself to determine what is going on with your local npm installs.

**Comment by dougwilson** [comment]
Unfortunately I cannot reproduce the issue you are seeing. I even looked at the literal bytes that are in the npm registry and in GitHub and they have the same MD5 hash:
```
$ npm info cookie-session@2.0.0-alpha.1 time.modified
2015-10-12T06:14:37.990Z

$ npm info cookie-session@2.0.0-alpha.1 dist.tarball
http://registry.npmjs.org/cookie-session/-/cookie-session-2.0.0-alpha.1.tgz

$ curl -s $(npm info cookie-session@2.0.0-alpha.1 dist.tarball) | tar -Ozx package/index.js  | md5sum
862484ec959fb35feb9fc38fd5515f96 *-

$ curl -s https://raw.githubusercontent.com/expressjs/cookie-session/2.0.0-alpha.1/index.js | md5sum
862484ec959fb35feb9fc38fd5515f96 *-

$ curl -s https://raw.githubusercontent.com/expressjs/cookie-session/1.2.0/index.js | md5sum
5db6eeacf38dd2b93f2ae825384b1dba *-
```

If cleaning your cache does not work, you may need to open a support issue (https://github.com/npm/npm/issues) with NPM itself to determine what is going on with your local npm installs.

**Comment by alvarotrigo** [comment]
I've just cleaned the cache `npm cache clean` and it seems the problem was solved. 
Thanks for the support in any case!

**Comment by dougwilson** [comment]
It's no problem, I'm glad I was able to help with this one :) I'm not sure why, but npm seems to get a corrupted cache too often.
