### ISSUE TITLE
Secure CookieSession when using iisnode

### ISSUE THREAD

**Issue by alvarotrigo** [expressjs/cookie-session#50]
I'm using node with IIS by using [iisnode](https://github.com/tjanczuk/iisnode) and I'm having troubles setting the CookieSession option `secure:true`.

I'm using HTTPS on IIS and I'm redirecting any HTTP to HTTPS.
But evenw ith this, if I set the [CookieSession](https://github.com/expressjs/cookie-session) option `secure:true`, the session won't have any content after login.

> **secure:** a boolean indicating whether the cookie is only to be sent over HTTPS (false by default for HTTP, true by default for HTTPS).

I'm forced to use `secure:false` to make it work. Why is it?

**Comment by dougwilson** [comment]
Hi! From the documentation, if you are not performing SSL at your Node.js process (and, of course with iisnode, you cannot be), you need to set `secureProxy: true` instead of `secure:true`. Let me know if that doesn't fix the issue!

**Comment by alvarotrigo** [comment]
@dougwilson thanks for it! It solved it. 
Sorry for it, It seems I didn't read the docs with much attention!

**Comment by dougwilson** [comment]
No problem! The docs here are not in the greatest state anyway. Always feel free to shoot a PR over (even just using the Github inline editor) if you think something can be tweaked/improved! One day I hope to go over this readme and get it in a better state, but I just don't know when that will be :(
