### ISSUE TITLE
Delete session after closing browser

### ISSUE THREAD

**Issue by alvarotrigo** [expressjs/cookie-session#51]
I didn't manage to remove the session after the browser gets closed.

My initialization:

``` javascript
app.use(cookieSession({
  maxAge: 8*60*60*1000, //8 hours
  httpOnly: true,
  secure: false,
  secureProxy: true,
  keys: ['key1', 'key2']
}));
```

> expires: a Date object indicating the cookie's expiration date **(expires at the end of session by default).**

**Comment by dougwilson** [comment]
Hi @alvarotrigo , sorry, I still have never gone through the documentation to fix anything. When you set the `maxAge`, under the hood all it does is set the expires, so setting it means that you've effectively set expires, canceling out any default behavior.

**Comment by alvarotrigo** [comment]
Right, now it makes more sense. Thanks for the explanation!
