### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rnjailamba** [expressjs/cookie-session#54]
I am using cookie-session and the cookie does not get created on it its own when i browse any page in my web app.
Code - 
```js
var cookieSession = require('cookie-session')//http://goo.gl/IImRVj
var cookieParser = require('cookie-parser');
app.use(modules.cookieParser());// read cookies (needed for auth)
app.use(modules.cookieSession({
  name: 'session',
  keys: ['mysecretty'],
  maxAge : 365 * 24 * 60 * 60 * 1000
}))
```

However a cookie of name "session is created when i add this line -
```js
app.use(function(req, res, next) {
  req.session.foo = 'bar';
  next();
});
```

I do not use livereload in my web app

**Comment by rnjailamba** [comment]
This seems similar to the description of this parameter - 
https://github.com/expressjs/session#saveuninitialized

**Comment by rnjailamba** [comment]
Also when i

**Comment by rnjailamba** [comment]
bump @dougwilson

**Comment by rnjailamba** [comment]
Is this answer correct - 
http://stackoverflow.com/questions/31980008/express-cookiesession-doesnt-populate-req-session

**Comment by dougwilson** [comment]
Hi @rnjailamba, this is an area that needs to be improved in the documentation. No cookie is set until there is something to actually have in the cookie in the first place. This means that if you don't set something in `req.session`, there is no data for this module to even store in the cookie, so you will not see a `Set-Cookie` response header.

**Comment by rnjailamba** [comment]
@dougwilson 
Thanks for this and changing the docs!
