### ISSUE TITLE
Storage of req.session.foo = 'bar';

### ISSUE THREAD

**Issue by rnjailamba** [expressjs/cookie-session#55]
Where is this stored?
In memory in the node js server / the browser.
I didnt see it in the browser so i presume it is in memory.

**Comment by rnjailamba** [comment]
According to https://github.com/expressjs/cookie-session#max-cookie-size
"Because the entire session object is encoded and stored in a cookie ......"
So i think the expected behaviour is to store it in the cookie itself but this is all i get

**Comment by rnjailamba** [comment]
bump @dougwilson

**Comment by dougwilson** [comment]
Hi @rnjailamba, the values are stored in the cookie that is sent to the web browser in the `Set-Cookie` response header, and not in-memory on the web server. Let me know if there is anything in the documentation we can improve to bring further clarity :)!
