### ISSUE TITLE
secureProxy deprecated in cookies 0.6.0

### ISSUE THREAD

**Issue by djmitche** [expressjs/cookie-session#59]
https://github.com/pillarjs/cookies/blob/8d7dd7739b81f5d434a66e6a0b47053fd792c5da/History.md#060--2016-02-29

`cookie-session` does not provide a way for me to pass `secure: true` to the `Cookie` constructor.

**Comment by djmitche** [comment]
Hm, I see that 1.2.0 requires cookies 0.5.0.

**Comment by dougwilson** [comment]
Hi @djmitche, yes, there is no way to currently pass in options, but the version we depend on has no options. When we get the version upgraded, we'll add some kind of API to enable this.

**Comment by Pointotech** [comment]
So what's the solution to this?
