### ISSUE TITLE
Release 2.0.0-alpha as stable?

### ISSUE THREAD

**Issue by wbecker** [expressjs/cookie-session#60]
It's been like 8 months now since -alpha was released... Should the alpha flag be removed and it published as stable?

**Comment by dougwilson** [comment]
Hi! Sorry I have let it sit for a while; there are actually a bunch of issues that still need to be ironed out, so no, it is just nit ready to be released as stable :(

**Comment by wbecker** [comment]
It might be good if 1.2 were tagged as latest in npm then, as it shows up as an upgrade when I run npm outdated!

See http://jbavari.github.io/blog/2015/10/16/using-npm-tags/

> This has happened to me thousands of times. I’ve run npm publish without specifying a tag, and now, my latest points at an alpha version.
