### ISSUE TITLE
Cookie options are not passed to cookies properly

### ISSUE THREAD

**Issue by tnguyen14** [expressjs/cookie-session#62]
After spending some time investigating, I'm seeing an issue that I wonder if it is a valid issue.

I'm seeing that when my session changes, I don't see that change being updated. I think this has to do with the cookie, on being set, is appended and not overwritten. I thought the default behavior of this plugin is to set `overwrite` to `true`.

Upon digging deeper into the code, I see that on this line, https://github.com/expressjs/cookie-session/blob/master/index.js#L64, 

```
    req.sessionOptions = Object.create(opts)
```
the session options is created as an empty object. `Object.create` will create the an new empty object, with `opts` as its prototype. `req.sessionOptions` however is just `{}` at this point.

Later on, when `sess.save()` is called, it passes `req.sessionOptions` to `cookies.set` as `opts` https://github.com/expressjs/cookie-session/blob/master/index.js#L239. However, since `req.sessionOptions` is `{}`, `overwrite` is not respected.

This might affect other cookie options as well, but `overwrite` was what I got stuck on.

Is this a valid issue? If so, I would propose we change the code on line 64 above from `Object.create` to something such as `Object.assign({}, opts)`.

**Comment by dougwilson** [comment]
I cannot reproduce the issue. an you provide a test case that demonstrates the issue? `console.log(req.sessionOptions.override)` is showing the setting just as I specified (`ture` in my case).

**Comment by tnguyen14** [comment]
@dougwilson Hmm. Then perhaps I was mistaken.

Would you know some reasons why I have 2 cookies of the same name on the client?

**Comment by dougwilson** [comment]
> Would you know some reasons why I have 2 cookies of the same name on the client?

Many cookies with the same name are very much allowed in the web browser. The server cannot tell why that is, so you have to be careful to always set a cookie with the same attributes. Can you list the attributes on each cookie with that name in the browser to see which attribute(s) differ?

**Comment by tnguyen14** [comment]
Thanks for the response!

Here's the problem I'm trying to figure out - I'm using passport google OAuth for authentication. Once the access token is expired (Google returns a 403), I redirects back to Google Sign in to get the new token. I can see that I receive a new token back from the provider, but for some reason the session cookie is still holding on the the old one, causing it to be stuck in a 403 redirect loop.

So the attribute that should change in this case is the accessToken.

When I go to Chrome's browser settings and look at the cookies for the site, I see the latest one. However, in the request header in the Network tab, I see that 2 cookies are set, the first one is the old one, and the second one is the newer one.

**Comment by dougwilson** [comment]
Gotcha. So when I say attributes, I'm referring to the cookie attributes like domain, path, secure, httpOnly, etc. The only reason a browser would not overwrite a cookie with the same name and have more than one copy is because at least one of those attributes differ. I'm not familiar with how to check that in Chrome, but that would be the most likely reason the browser is sending two values to the server.
