### ISSUE TITLE
how to use redis with cookie-session

### ISSUE THREAD

**Issue by superlbr** [expressjs/cookie-session#63]
come on

**Comment by blakeembrey** [comment]
@superlbr "come on"? This project, as far as I know, has zero relationship to any database. It's based on signed cookies instead. Perhaps you can provide more details of what you actually want to do?

**Comment by blakeembrey** [comment]
Perhaps you are interested in https://github.com/expressjs/session#compatible-session-stores, which is linked in the README in the explanation of cookie size limits. It's much more cost effective to store sessions in signed cookies are a shared database.

**Comment by superlbr** [comment]
if one of multi-servers down,how should i recovery cookie?

**Comment by blakeembrey** [comment]
All the cookie data is stored in the cookie. All the information you need should be in the README.
