### ISSUE TITLE
Cookie-options not set(again)

### ISSUE THREAD

**Issue by enhaster** [expressjs/cookie-session#65]
It's me again :) 

Maybe i do something wrong, but default settings still not working.

Here is the code:

```
var cookieSession = require('cookie-session');
app.use(cookieParser());

app.use(cookieSession({
    name: 'session',
    secret: 'dexter',
    cookie: {       
        secure: true,
        httpOnly: true,
        maxAge : 1111
    }
    })
);

app.get('/login', function(req, res, next) {
req.session.someid = 'bar';
res.render('login');
});
```

And there is chrome developers-tool(F12/Network):

``` Cache-Control:max-age=0
Connection:keep-alive
Cookie:session=eyJycnIiOiJkc3NzcyIsInRlc3QiOiJkc3NzcyIsImZvbyI6ImJhciIsInNvbWVpZCI6ImJhciJ9; session.sig=RoXWvswDSKg8qoZS5ePtVn1jl3Q
```

maxAge is not set to 1111 :(  

What i do wrong?

**Comment by dougwilson** [comment]
Hi! What you are showing from the Chrome dev tools is the `Cookie` header, which is in the request, not the response. The `Cookie` header is only name value pairs; the max age would only appear in the `Set-Cookie` header, which is in the response.

**Comment by enhaster** [comment]
Thanks, i find it(on tab cookie and make it work!).

But it's strange, that is working only like that:
```app.use(cookieSession({
	name: 'session',
	secret: 'dexter',
	maxAge : 1111,    
	cookie: {		
		secure: true,
                httpOnly: true  
	}
})
);
```
And not that
```
app.use(cookieSession({
	name: 'session',
	secret: 'dexter',
	   
	cookie: {		
		secure: true,
                httpOnly: true ,
                 maxAge : 1111
	}
})
);
```

Oh, and i need to change secret :)

And if you not boring from, can you please tall, can i use massive to set many value:key in 1 row (req.session.someid = 'bar4'; //and bar5, 6.... )

**Comment by dougwilson** [comment]
Hi @enhaster sorry I missed the notification on your response for this oh-so-long-ago :) I'm not really sure what is going on with your example, as I'm not able to reproduce the issue. If you're feeling up for it, please feel free to put together a pull request with a fix, as the `maxAge` should only be working when it's inside the `cookie` object, not outside it.
