### ISSUE TITLE
req.sessionOptions is always empty

### ISSUE THREAD

**Issue by jmcoimbra** [expressjs/cookie-session#67]
Hello,

Just executing the sample code you provide I cannot access the cookie options via `req.sessionOptions`.

For instance: if I am going to use it via a simple REST API to authenticate browsers' users I don't know if their cookie expired and how to request a new one.

Thanks

----
For all matters, this is the code I am using to check it:
```javascript
var cookieSession = require('cookie-session')
var express = require('express')

var app = express()

app.set('trust proxy', 1) // trust first proxy
var opt = {
  name: 'session',
  keys: ['key1', 'key2'],
  // maxAge: 24 * 60 * 60 * 1000, // 24 hours
  expires: new Date(new Date().getTime() + 1*60000) // 30 minutes
};

console.log(JSON.stringify(opt))

app.use(cookieSession(opt))

app.get('/', function (req, res, next) {
  // Update views
  req.session.views = (req.session.views || 0) + 1

  console.log(req.sessionOptions)

  // if (req.sessionOptions.expires < new Date().getTime()) {
    console.log('session: ' + JSON.stringify(req.session))
    res.end(req.session.views + ' views') // Write response
  // }
  // else {
  //   req.session = null
  // }
})

app.listen(3000)
```

**Comment by dougwilson** [comment]
What you are seeing in a limitation of how `console.log` works in Node.js. It is not actually empty. Just do `console.log(req.sessionOptions.name)` for example, and you'll see the name is indeed there.

**Comment by jmcoimbra** [comment]
Ok, I see.

Even using [util.inspect](https://nodejs.org/api/util.html#util_util_inspect_object_options) it is showing as an empty object. Also with [Object.keys](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/keys) - everything pretty odd for me.

Then I guess the front end must check if the cookie is expired, delete it and request a new one.

Thanks for your help @dougwilson!
