### ISSUE TITLE
Cookie path

### ISSUE THREAD

**Issue by kol9n93** [expressjs/cookie-session#69]
Hi. I'm trying to save cookies by path like this:
```
app.use(session({
  name: 'test.connect.sid',
  keys: ['key1', 'key2'],
  cookie: {
    secure: false,
    domain: 'localhost',
    path: '/test',
    expires: expiryDate
  }
}));
```
But when I look on cookies in browser I see the following:
![cook](https://cloud.githubusercontent.com/assets/8199096/20967037/597d6a9a-bc8e-11e6-9fd7-d66e926ce868.PNG)
Path is default, '/', expire date is default too.

**Comment by dougwilson** [comment]
There is no "cookie" option object. All the options are at the top level:
~~~
app.use(session({
  name: 'test.connect.sid',
  keys: ['key1', 'key2'],
    secure: false,
    domain: 'localhost',
    path: '/test',
    expires: expiryDate
}));
~~~
You should probably use maxAge and mot expires, otherwise you'll have to restart the server once that date passes.

**Comment by kol9n93** [comment]
Thank you

**Comment by kol9n93** [comment]
May be you know: I changed default path and then I lose all session data after any redirect.
