### ISSUE TITLE
Express lose session after redirect when cookie-session path is different from default

### ISSUE THREAD

**Issue by kol9n93** [expressjs/cookie-session#70]
Hi again. I have the following problem: I've changed session cookie path from default '/' to '/test'. 
```
app.use(session({
  resave: true,
  name: 'test.connect.sid',
  keys: ['key1', 'key2'],
  secret: 'testsecret',
  secure: false,
  domain: 'localhost',
  path: '/test'
}));
```
My /test1 route sets test string to the session. 
```
app.get('/test1', function(req, res, next) {
    req.session.test = 'test';
    res.redirect('http://localhost:3000/test2');
});
```
Before redirect I have a test string in request session, but after redirect to '/test2' request session is undefined.
```
app.get('/test2', function(req, res, next) {
    console.log('test2', req.session.test); // undefined
    res.send(req.session.test);
});
```
When session cookie path is default ('/') all works as expected. But I need a different cookie paths.
May be you know how to fix it?

**Comment by dougwilson** [comment]
So the issue is not the redirect, rather it is just how cookies work in web browsers. If you set the cookie path to /test, it is only accessible under /test. Since /test2 is not that path, the browser simply never even sends the cookie to the web server.

**Comment by kol9n93** [comment]
But I lost the session on server, not cookies

**Comment by dougwilson** [comment]
Maybe you're posting in the wrong repo? This is cookie-session: there is no session on the server, as the entire session contents are in the cookie directly.
