### ISSUE TITLE
The same session id 

### ISSUE THREAD

**Issue by ideal-life-generator** [expressjs/cookie-session#76]
Hi, why I have the same session id in cookie all time
```
{
  session: 'eyJpc0F1dGhvcml6ZWQiOnRydWV9',
  'session.sig': 'MQ71ACs_SuMd_6CqtSXfwd91zoE'
}
```
I used different browsers, delete cookies from browser, reload server. But is the same `eyJpc0F1dGhvcml6ZWQiOnRydWV9` combination all time. Is ok, or I don't understand something :D I thought session id must be unique all time...

The options:
```
{
  keys: ['mix of the drink', 'another mix of the drink :DD'],
}
```

The [repo](https://github.com/ideal-life-generator/MyApp/blob/master/src/server.js).

**Comment by dougwilson** [comment]
Hi @ideal-life-generator this module doesn't store session IDs at all; the entire session is in that cookie. The value `'eyJpc0F1dGhvcml6ZWQiOnRydWV9'` is just a Base64 encoded JSON object. You can decode it yourself:
```
$ node -pe 'JSON.parse(new Buffer("eyJpc0F1dGhvcml6ZWQiOnRydWV9","base64").toString())'
{ isAuthorized: true }
```

**Comment by dougwilson** [comment]
The reason it's always the same in your repo is because the only thing you do with the session is `req.session.isAuthorized = true` so all users will have a session that is identical to each other, just containing `{ isAuthorized: true }`

**Comment by ideal-life-generator** [comment]
Hi. Thank you for fast answer :DD So, what I must to do, is just add some unique data? Ok, now I understand)
Have a nice day!

**Comment by dougwilson** [comment]
Yea, typically if the session is related to authentication, you would need to store _who_ in the session (like the username, userid, or something like that). That would of course then make the cookie's value different per user (and the `key` signs the cookie so even if you know another user's username, you cannot actually create a cookie value unless the `key` is leaked from the server).

**Comment by RevealedFrom** [comment]
> the entire session is in that cookie. The value 'eyJpc0F1dGhvcml6ZWQiOnRydWV9' is just a Base64 encoded JSON object. 

Is the function to verify the cookie against `session.sig` exposed so that I can read session variables securely in a module (socket.io) that is not in the Express route?
