### ISSUE TITLE
Ajax calls won't update the session

### ISSUE THREAD

**Issue by alvarotrigo** [expressjs/cookie-session#78]
I'm not quite sure if this has anything to do with https://github.com/expressjs/cookie-session/issues/75
But when calling a route to update the session through an ajax call (`$.get`), the session will not get updated. 

Only when accessing the route directly through the URL, the session will get updated.

```javascript
router.get('/demo', function(req, res, next) {
         req.session.demo = 'aaaa';
         next();
});
```

```javascript
    $.get(url);
```

**Comment by dougwilson** [comment]
Weird. The only thing I can think of off-hand is that your code doing the AJAX is in a different origin than the server, and as such browsers by default drop cookies I believe. Any code or something you can provide so I can poke at it?

**Comment by dougwilson** [comment]
Closing since I never heard back.
