### ISSUE TITLE
Get all sessions at server side

### ISSUE THREAD

**Issue by apmeena** [expressjs/cookie-session#82]
I am using [Passportjs](http://passportjs.org/) and [cookie-session](https://github.com/expressjs/cookie-session) with [Express js](https://expressjs.com/) for authentication. I want the list of all logged in users at server side but I am not able to do that.

In order to get the session value, I need to do something like this `req.session`, 
but it gives the session values related to current request only. Is there any why go get all session value in one go?

Thanks.

**Comment by dougwilson** [comment]
It is not possible when the sessions are stored client side, which is what this module does. You can only do that if you store the sessions server side, which is what express-session does. I hope that helps!
