### ISSUE TITLE
New session on every request

### ISSUE THREAD

**Issue by caseyryan** [expressjs/cookie-session#83]
I've setup cookie-sessions exactly according to the instructions to test its work. But I get new session on every request:
Here's the initialization code:
`app.use(cookieSession({
    name: 'session',
    keys: [Constants.COOKIE_SESSION_KEY_1, Constants.COOKIE_SESSION_KEY_2]
}));
app.use(function (req, res, next) {
    req.sessionOptions.maxAge = 60000;
    next();
})`

And here's the testing one:

```
router.get('/auth', function(req, res, next) {

    console.log("SESSION BEFORE:", JSON.stringify( req.session), req.session.isNew);
    res.json({ok: 'ok'})
    req.session.test = 1;
    console.log("SESSION AFTER:", JSON.stringify(req.session));
}
```
It always gives me this output:

> SESSION BEFORE: {} true
> SESSION AFTER: {"test":1}

I'm doing fetch() requests with credentials: 'include' option. 
I used client-sessions module before and it could set cookie

Am I missing anything?

**Comment by dougwilson** [comment]
Hi @caseyryan , the `cookie-sessions` module you mentioned at the top is actually a different module: https://github.com/caolan/cookie-sessions

**Comment by caseyryan** [comment]
No no, sorry, my bad, i've just mistyped it here. It's definitely cookie-session. Not cookie-sessions.
But I found the problem already. It's because I finalized the response before the cookie was actually sent. I'm new to node.js and express, so I didn't know that red.json will end it as well. Cookie-session works fine :)

**Comment by dougwilson** [comment]
Ah, oops! I wasn't 100% sure and since there is a cookie-sessions (confusingly, I know) that is also a connect / express middleware, and there wasn't another mention I wasn't sure. Yea, looking at your code, I see that now as well. Since the session is serialized into the cookie, the session needs to be complete before responding, haha. `res.json` does cause a response, which is what you observed as well.

Sorry for the premature closure!

**Comment by caseyryan** [comment]
The problem appeared again. The cookie is set normally and I can check it many times, everything's ok. Then I call another route to destroy session and give it a value of null, simply like this:
`req.session = null`
After this, I can't assign new values to the session because it always gives me new session

**Comment by caseyryan** [comment]
as I found out, internally it uses 'cookie' dependency. And inside 'cookie' it fails on line 76 in this code block
```
if (index < 0) {
    this.set(sigName, null, {path: "/", signed: false })
  } else {
    index && this.set(sigName, this.keys.sign(data), { signed: false })
    return value
  }
```
Index here is less than 0 after that
I understand it's not the code of cookie-session module but since it uses cookie as a dependency, maybe that'll help you to see what's wrong with this. I've been struggling with this problem for almost 3 days now, to no avail so far :(

**Comment by caseyryan** [comment]
I found another strange issue. It doesn't work only from callbacks. In my code, you can see callback function as a third argument of login function. If I set session from there, it will say SESSION IS SET, but when I check it, it gives me a new empty session. 
But if I remove any callbacks and just write the code like this:

```
 if (act == Constants.ACT_LOGIN_CHECK) {
        console.log('SESSION CHECK >>> ', JSON.stringify(req.session), req.session.isNew);
        res.send(`SESSION CHECK >>> ${JSON.stringify(req.session)} ${req.session.isNew}`);
    } else if (act == Constants.ACT_LOGIN_REQUEST) {
        req.session.testKey = '2';
        req.session.save();
        console.log('SETTING SESSION >>> ', JSON.stringify(req.session), req.session.isNew);
        res.send(`SESSION SET >>> ${JSON.stringify(req.session)} ${req.session.isNew}`);
    } else {
        req.session = null;
        console.log(`SESSION KILLED >>> ${JSON.stringify(req.session)}`);
        res.send(`SESSION KILLED >>> ${JSON.stringify(req.session)}`);
    }
    return;
```
Everything works. But setting the session from inside the callback is only reasonable thing here. I just can set anything until I get the necessary data from social network. Looks like a dead end...

**Comment by dougwilson** [comment]
Hi @caseyryan weird, if I run only the code you provided above, where I just made my `login` function `setTimeout` internally and then setup the most minimal Express around that route you gave as the only route, setting the session inside the callback did work fine. This means that the issue is somewhere between the minimal case I created and your full app. Since I can't see any other code than what you posted above, I'm not sure what the difference is. Here is the app I made:
```js
var express = require('express');
var cookieSession = require('cookie-session');

var app = express();
app.use(cookieSession({
  name: 'session',
  keys: ['foo', 'bar']
}));

app.get('/auth', function(req, res, next) {
  console.log("SESSION BEFORE:", JSON.stringify( req.session), req.session.isNew);
  var params      = req.query;
  var act         = params.act;

  switch (act) {
    case 'check':
      console.log('SESSION CHECK >>> ', JSON.stringify(req.session));
      res.end();
      break;
    case 'login':
      var code        = params.code;
      var state       = params.state;
      login(code, state, function(result) {
        if (result) {
          if (result.accessToken) {
            console.log("WRITING SESSION BEFORE: ", JSON.stringify(req.session), req.session.isNew);
            req.session.accessToken = result.accessToken;
            req.session.userId      = result.userId;
            req.session.firstName   = result.firstName;
            req.session.lastName    = result.lastName;
            req.session.photoURL    = result.photoURL;
            console.log("SESSION IS SET: " + JSON.stringify(req.session), req.session.isNew);
            res.end(); 
          } else {
            req.session = null;
            res.end();
          }
        } else {
            req.session = null;
            res.end();
        }
      });
      break;
    case 'logout':
      req.session = null;
      res.end();
      break;
  }
});

app.listen(3000);

function login(code, state, cb) {
  setTimeout(function () {
    cb({
      accessToken: 'token',
      userId: 42,
      firstName: 'john',
      lastName: 'doe',
      photoURL: null
    });
  }, 2000)
}
```


And here is me trying to run it, getting the session cookie even with the async login call and the check validating it:
```
$ npm i express cookie-session
npm WARN saveError ENOENT: no such file or directory, open '/Users/doug.wilson/Code/cookie-session-83/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/doug.wilson/Code/cookie-session-83/package.json'
npm WARN cookie-session-83 No description
npm WARN cookie-session-83 No repository field.
npm WARN cookie-session-83 No README data
npm WARN cookie-session-83 No license field.

+ cookie-session@2.0.0-beta.2
+ express@4.15.3
added 50 packages in 2.926s

$ node app &
[1] 72517

$ curl -i http://127.0.0.1:3000/auth?act=login
SESSION BEFORE: {} true
WRITING SESSION BEFORE:  {} true
SESSION IS SET: {"accessToken":"token","userId":42,"firstName":"john","lastName":"doe","photoURL":null} true
HTTP/1.1 200 OK
X-Powered-By: Express
Set-Cookie: session=eyJhY2Nlc3NUb2tlbiI6InRva2VuIiwidXNlcklkIjo0MiwiZmlyc3ROYW1lIjoiam9obiIsImxhc3ROYW1lIjoiZG9lIiwicGhvdG9VUkwiOm51bGx9; path=/; httponly
Set-Cookie: session.sig=hiVuIyqScdW5vUbQQnqYidPfStU; path=/; httponly
Date: Mon, 03 Jul 2017 14:26:38 GMT
Connection: keep-alive
Content-Length: 0

$ curl -i -H'Cookie: session=eyJhY2Nlc3NUb2tlbiI6InRva2VuIiwidXNlcklkIjo0MiwiZmlyc3ROYW1lIjoiam9obiIsImxhc3ROYW1lIjoiZG9lIiwicGhvdG9VUkwiOm51bGx9; session.sig=hiVuIyqScdW5vUbQQnqYidPfStU' http://127.0.0.1:3000/auth?act=check
SESSION BEFORE: {"accessToken":"token","userId":42,"firstName":"john","lastName":"doe","photoURL":null} false
SESSION CHECK >>>  {"accessToken":"token","userId":42,"firstName":"john","lastName":"doe","photoURL":null}
HTTP/1.1 200 OK
X-Powered-By: Express
Date: Mon, 03 Jul 2017 14:27:19 GMT
Connection: keep-alive
Content-Length: 0
```

**Comment by caseyryan** [comment]
@dougwilson thanks for trying to help, I really appreciate it. 
I found the reason of this issue today. Actually, my login function did request to social network for user credentials, and as it was the very first request of my app, the SN set its own headers right before I could set cookie. The reason why it worked from time to time is that I called my own "clear session" method before calling the social network sometimes and after that I could set my own headers. But due to my noobieness in JS programming I couldn't find it out for a few days.
Now I've resolved this issue by making the very first request to my own server. It just checks the cookie, sets the headers, and I can normally work with sessions from this moment on
p.s.  Maybe you could add some warning to people like me to be careful if they use OAuth authentication on some third party services like twitter that they might set undesirable headers which will break the app's sessions

**Comment by dougwilson** [comment]
Hi @caseyryan I can definitely add a warning, but I need more details on what is actually happening to be able to provide a detailed warning. So far I just have the following information:

> Warning: If you are using OAuth authentication on some third party services like twitter that they might set undesirable headers which will break the app's sessions

But that bring up a lot of question like which headers? Break it in what way? How can I solve the issue? etc. If you're not sure, that's OK! I'd be happy to figure it out, but I need to understand exactly what you're doing. Is it possible for you to send over an app with instructions that I can follow that reproduces the breakage you're describing?

**Comment by caseyryan** [comment]
Ok, to be exact, I've made authorization for 2 Russian social networks vk.com and ok.ru. They both have standard OAuth2 authentication process for websites and third party applications which described [here ](https://vk.com/dev/authcode_flow_user).
My setup islike this:
React-Redux frontend and Express backend api server. React is running on localhost:3000 and express is on localhost:3001. React proxies all requests to express. 
But as social network redirects a browser to 'redirect_uri' which I specify in my request to it and puts code and state params directly to the url, I can't do it via proxy, so I'm doing this:
`window.location.href = geLoginURL();`
It forms the proper request URL to social network so that it could return code and state to my app which I can use for getting access_token from my server. And the problem starts exactly after I do this action. The SN responds with code and state params and also sets it's own headers. After this I can't set my own session until I reload the whole page and do my first fetch() request to my API server. If the first request would be to my API server instead of VK, Odnoklassniki or Twitter,, the sessions will work like a charm
