### ISSUE TITLE
[docs] Please list the differences between cookie-session and express-session

### ISSUE THREAD

**Issue by mariusa** [expressjs/cookie-session#84]
For example, express-session stores cookie session in memory, so it's lost on every server restart. cookie-session is preserved (is this true?)

Thanks

**Comment by pjz** [comment]
Express-session stores session data into configurable backends, ranging from memory to any number of databases, thus allowing essentially unlimited session storage.

cookie-session stores session data into cookies, thus being limited to a bit under 4k bytes of session storage.

Most of the rest of the differences are consequences of this decision:
  * cookie-session works without depending on an external datastore (so less infrastructure to set up, configure, maintain)
  * cookie-session works behind load balancers without 'sticky-sessions' having to be enabled/configured.

**Comment by mariusa** [comment]
Thanks! Would be great to have this at
https://github.com/expressjs/cookie-session
as well (I would have found it useful)

**Comment by dougwilson** [comment]
That explanation sounds great! Please feel free to submit a pull request adding it to the README, otherwise I can add one soon :)
