### ISSUE TITLE
Backport `debug` update to fix `ms` vulnerability

### ISSUE THREAD

**Issue by AntJanus** [expressjs/cookie-session#85]
The 2.0.0-beta.2 has an update of the `debug` package which in turn features an update of the `ms` library which was identified to have a `regular expression denial of service` vulnerability.

Is there any way to backport this upgrade to the `1.2.x` releases? Maybe a 1.2.1 so that users can install a safe version of `cookie-session` without relying on an alpha/beta release?

**Comment by dougwilson** [comment]
Since the vulnerable API in the `ms` library is not used by the `debug` module, there is no vulnerability present. The `ms` module has two completely different code paths: (1) a parsing function and (2) a serialization function. The vulnerability is only in the parsing while `debug` only uses the serialization.

**Comment by AntJanus** [comment]
Thanks! :)

**Comment by dougwilson** [comment]
I am planning to release the 2.0.0 very soon, and it was just coming up in my today's todo, so that may be doable. The changes between 1.x and 2.x are not very big (just gotta write up a migration guide).

**Comment by dougwilson** [comment]
I'll look at backporting, though. As long as the Travis CI runs OK on that version, we should be good to backport.

**Comment by dougwilson** [comment]
Because the `debug` module went through several new features and deprecated something, I can't release the update as a 1.2.1, so it'll be 1.3.0 instead.

**Comment by dougwilson** [comment]
Published version 1.3.0

**Comment by AntJanus** [comment]
@dougwilson thank you! :)
