### ISSUE TITLE
Quoted vs Unquoted signed cookie values

### ISSUE THREAD

**Issue by markmeyerphoto** [expressjs/cookie-session#88]
I'm having a little trouble with signed cookies being sent to Twilio. I'm setting up a session cookie but I'm not getting the session back on subsequent requests from Twilio despite those requests having what looks like a good cookie header. Changing to unsigned cookies fixes the problem.  I have no problems when making requests through something like Postman. The only difference I can see between what Postman is sending and what Twilio is sending is that Twilio is wrapping the cookie value in quotes. So my question is: should quoted values break signed cookies?

Here is a typical header I'm getting from twilio that  results in an undefined req.session: 

    cookie: '$Version=1; session="eyJrbm93bl9jYXNlIjpmYWxzZSwiY2FzZV9pZCI6IjEyMzQ1NjcifQ=="; 
    $Path="/"; $Domain=xx.xx.xx.xxx; $Version=1; session.sig=DasSRyvhWnjYpCF0VKJIsrvbXAY; 
    $Path="/"; $Domain= xx.xx.xx.xxx',

vs. Postman:

    cookie: 'session=eyJrbm93bl9jYXNlIjpmYWxzZSwiY2FzZV9pZCI6IjEyMzQ1NjcifQ==;
    session.sig=DasSRyvhWnjYpCF0VKJIsrvbXAY',

The postman header works, the Twilios header doesn't, but I don't know enough about signed cookies to know where the problem is.

**Comment by dougwilson** [comment]
Hi @markmeyerphoto interesting I've never seen them quoted like that before. I think the underlying cookie parser will actually include the quotes in the value, so the quotes become part of the value, which would invalidate the signature. Do you know if this quoting is actually a part of a cookie spec somewhere?

**Comment by markmeyerphoto** [comment]
Hi @dougwilson -  RFC 6265 address doubles quotes in cookie values saying the octet may be double quoted:

    cookie-value      = *cookie-octet / ( DQUOTE *cookie-octet DQUOTE )

I'm not sure how implementations should interpret that in terms of signed cookies, but IMO if the octet is the same, it should be treated us unmodified even if it's quoted. I'm not sure how else it could work. 

I'll take a look and see if there's already an issue on the cookies module.

**Comment by dougwilson** [comment]
I see you opened an issue in the `cookies` module. I'm going to close this issue unless you think there is something that needs to be changed in this module 👍
