### ISSUE TITLE
encrypt cookies

### ISSUE THREAD

**Issue by defunctzombie** [expressjs/cookie-session#9]
Signing is nice, but a better thing might be to just encrypt the cookies outright. This serves the purpose of signing and also hiding the session details from user inspection.

**Comment by coen-hyde** [comment]
@nburoojy Can your encryption implementation be merged back into cookie-session?

**Comment by gabeio** [comment]
@coen-hyde he said it was a fork so it *should be* possible...

**Comment by sankethkatta** [comment]
Mozilla has a package which does just this: [mozilla/node-client-sessions](https://github.com/mozilla/node-client-sessions)

**Comment by dougwilson** [comment]
Hi @sankethkatta , yep, and it's a 100% valid alternative! `npm` gives you a lot of choice :)

**Comment by ebourmalo** [comment]
I was also looking for this option and didn't find anything. I made a super-easy to use express middleware to achieve transparently cookie encryption / decryption: [cookie-encrypter](https://github.com/ebourmalo/cookie-encrypter). 

```js
var app = express();
app.use(cookieParser(secretKey));
app.use(cookieEncrypter(secretKey));
```

Hope this helps

**Comment by btxtiger** [comment]
@ebourmalo did you get it working with cookie-session? It seems the session cookies were not caught by the middleware.

**Comment by dougwilson** [comment]
So apparently having stale issues is a sign of bad modules these days, who knew. This is still a desired feature that I plan to work on at some point, though anyone is welcome to make a PR as well. I'm going to close this issue, unfortunately, as just having it open down ranks the module.

**Comment by sawyerh** [comment]
@dougwilson Just confirming I'm not overlooking something: encryption support hasn't been added to `cookie-session`? Could this request be reopened if so?

**Comment by dougwilson** [comment]
It has not been added and as noted above I'm not going to reopen the issue, either, for those reasons. If you want to see it happen, the best thing to do is to put to together a pull request instead of us keeping an issue open indefinitely. Perhaps if someone committed to having a pull request made in a specific timeline I can open this issue. If you want to make that commitment, let me know and I can reopen.

**Comment by btxtiger** [comment]
@dougwilson
You can check out my node module, if it fits to your requirements.
https://github.com/btxtiger/encrypt-cookie

**Comment by mircohaug** [comment]
@dougwilson my PR for this feature is ready. Please have a look.
