### ISSUE TITLE
How to set cookie for all site?

### ISSUE THREAD

**Issue by tapinambur0508** [expressjs/cookie-session#90]
Hello. I recently got acquainted with your package. It's very good package, but I have some problem. I want to set cookie for all website. How I can do it?

**Comment by dougwilson** [comment]
Hi @tapinambur0508 that sounds like how this module works by default, but perhaps we have a different understanding from your description. Can you elaborate?

**Comment by tapinambur0508** [comment]
Now I use this:
`app.use(cookieSession({
  maxAge: 24 * 60 * 60 * 1000,
  keys: [sessionConfig.cookieKey]
}));
`
But cookie set only on index page. I want that cookie set in page like this /article/59dd037b734d1d55d0f1382e. I work on localhost

**Comment by dougwilson** [comment]
Hi @tapinambur0508 you're still describing the default behavior. If you're seeing something different, maybe there is a bug somewhere. Can you help me reproduce the issue to take a look at what is happening? Please provide all the following:

1. Version of Node.js you are using.
2. Version of this module you are using.
3. Complete source code where I don't have to fill anything in so we have the exact same code on both our sides.
4. Instructions for how to reproduce the issue, with the exact things to load and click.

Thank you!

**Comment by tapinambur0508** [comment]
I'm sorry to trouble you. This is my mistake
