### ISSUE TITLE
Typescript: Type 'null' is not assignable to type 'CookieSessionObject'

### ISSUE THREAD

**Issue by pamtbaau** [expressjs/cookie-session#93]
`req.session = null;`
> error TS2322: Type 'null' is not assignable to type 'CookieSessionObject'

`req.session = undefined;`
> error TS2322: Type 'undefined' is not assignable to type 'CookieSessionObject'

**Comment by dougwilson** [comment]
Hi @pamtbaau I'm not familiar with Typescript, so not sure what this means. Do you know what the solution is / what changes we would need to make here?

**Comment by pamtbaau** [comment]
When installing Typescript types for cookie-session by `npm install @types/cookie-session`, the file `node_modules/@types/cookie-session/index.d.ts` contains the types for variables, interfaces, classes, etc..

That file (line 100) tells Typescript that `session` can only be assigned a value of type `CookieSessionObject` and nothing else.

Adding the following change to index.d.ts (line 100) will solve the error.

```
    interface CookieSessionRequest {
        ...
        // change 
        session: CookieSessionObject;
        // into
        session: CookieSessionObject | null | undefined;
        ...
    }
```

Now a value of type `CookieSessionObject` or `null` or `undefined` can be assigned to `req.session`.

NB. If code expects session to be of type `CookieSessionObject` or `null` then remove `undefined`.

**Comment by dougwilson** [comment]
Ah, interesting. Where does that file come from? I don't think we have that in our repo, right? How do I make the change?

**Comment by pamtbaau** [comment]
Not sure how this works, but from

- [https://www.npmjs.com/package/@types/cookie-session](https://www.npmjs.com/package/@types/cookie-session)
- I landed at [DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), a repository for TypeScript type definitions.
-  where the following folder can be found [DefinitelyTyped/types/cookie-session/](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/cookie-session) containing the `index.d.ts` mentioned above. The latest commit is from Nov 8, 2017.

I don't know the process behind this repository. Maybe you can fork the repository, create changes and issue a pull request. I don't know...

**Comment by dougwilson** [comment]
Gotcha. I'm not really familiar either, and of course not understanding TypeScript makes me not the best candidate to be making these changes, either. If there is something we should change in this repository / module let us know / even make a PR. If you're saying the issue at had is actually a different repo / module, then you may want to open an issue there 👍
