### ISSUE TITLE
Set Cookie as post response?

### ISSUE THREAD

**Issue by rscharfer** [expressjs/cookie-session#95]
It could very well be that I am missing something basic here, but why cannot I set a cookie as a response to a cookie?
Here is my over simplified code that does not set a cookie for some reason:
`app.post('*', (req,res) => {
	req.session.userName = "John Doe";
	res.end()
})`
My use case would be when the user logs in, the body of the post is parsed, and the name she logged in with will be saved to the session cookie.

Setting cookies as responses to get requests is not a problem.

**Comment by rscharfer** [comment]
Here is info they may or may not be pertinent.  When the http post request comes from Postman, the cookies are returned from the server. When the request comes from my browser, cookies are not returned.   The express server is current hosted on localhost:3000.  Is this a cross-domain thing?

**Comment by dougwilson** [comment]
Hi @rscharfer I tried to put together an app with that line in it and (using Chrome) it set the cookie just fine on POST. There are a lot of differences we may have going on here. Can you provide all the following so I can try to reproduce to see what is happening?

1. Version of Node.js
2. Version of this module
3. Complete app code (not just a single line)
4. Instructions on how to start your app and then the steps to reproduce (load browser, go to address ... click ... etc).

Thanks!

**Comment by rscharfer** [comment]
Hi @dougwilson. Thanks for looking into this!

3. You can clone the repo with `git clone https://github.com/rscharfer/cookiesessiontest.git`
4. Once the repo is cloned, step into it `npm install`  and 'npm run watch'.  The app should be running on your localhost.  You can click on "Captivate Dummy" and use one of the valid user name and passwords listed to fill in the form.  Once you submit the form,  line 129 of app.js should catch the post request
  
`app.post('*', isAuthenticated, (req,res) => {
	req.session.name = "User Name";
	console.log("where is the cookie?")
	res.end()
})`

and the `console.log("where is the cookie")` will indicate the post request has been received. Yet, in my Chrome browser, there are no cookies.


![nocookie](https://user-images.githubusercontent.com/4295997/35496493-5658c6ee-04c6-11e8-8fee-8b0bc575f783.PNG)


Any ideas you have would be great!

**Comment by rscharfer** [comment]
I think this somehow has to do with this issue I am still having: https://stackoverflow.com/questions/47712162/how-do-i-get-express-to-render-html-after-a-post-request?noredirect=1#comment82405039_47712162

**Comment by rscharfer** [comment]
So this does not seem to be a localhost issue as I had thought.  I still have the same problem when my app is hosted on AWS.

**Comment by dougwilson** [comment]
Hi! Thanks so much for getting that for me! I was thinking of looking into this today, but I think I instead need to focus on https://github.com/expressjs/generator/pull/190#issuecomment-361248460 as it sounds more urgent I think. Once that is done, I'll come back to this next, but it is unlikely to be today, very sorry :(

**Comment by rscharfer** [comment]
Hi there. I figured it out! I was making the POST with fetch() on the client side, and I needed to add `credentials: 'same-origin'` to the fetch() configuration object.  : )   I still do not know why the browser will not render text or html when I respond to a POST request with that, but that's a topic for a different forum. (You can see the body of the response in the browser dev tools, but for whatever reason, the browser doesn't render it.)  Anyway, thanks for the help!!
