### ISSUE TITLE
Session save does not support a callback url

### ISSUE THREAD

**Issue by purpleD17** [expressjs/cookie-session#98]
Cookie session does not implement the documented interface for express session `save`. As you can see here :
https://github.com/expressjs/session/blob/8e57b21bef0d53010c4d37f4beee3f0341f3eaa6/session/session.js#L71

and per the documentation here: https://github.com/expressjs/session#sessionsavecallback

Save should take an optional callback method. The background is i'm trying to implement this fix:  https://github.com/jaredhanson/passport/issues/482#issuecomment-230594566 But I can't since there is no callback url

**Comment by dougwilson** [comment]
The interface documentation you linked to is for `express-session`, which this module is not trying to comply with. Regardless, I can add an optional to this module's `.save()` method for parity. Do you need the new callback in the stable version, or is the beta version fine?

**Comment by dougwilson** [comment]
It probably doesn't matter at this point, as the 1.x series is about to be deprecated with the release of 2.0.

**Comment by rakeshkatti** [comment]
@dougwilson, Is this being considered in 2.0?

**Comment by dougwilson** [comment]
Yea, though because I got no response from OP I completely forgot about this issue. Is anyone willing to put together a PR? I can do it as well, probably in Jan.

**Comment by dougwilson** [comment]
Sorry I didn't get to doing this. No PR came up either, and as I was about to do this, I noticed that save was never a documented method and the JSDoc marks it as a private API, so probably best just to actually remove the ability for users to call it at all from 2.0 to prevent confusion. Calling `.save()` just generates a cookie value and is a sync action, so has no purpose in this module.
